[package]
name = "anise_test"
version = "0.1.0"
edition = "2024"

[dependencies]
aethervk-core-rlib = { path = "../../aethervk.core/rlib", default-features = false }
aethervk-oshal-rlib = { path = "../../aethervk.oshal/rlib", default-features = false, features = ["console_log"] }
anise = { path = "../../external/anise/anise", default-features = false }
bytes = { version = "1.11.1", default-features = false }
libc = { version = "0.2", default-features = false, features = ["extra_traits"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[target.'cfg(target_env = "msvc")'.dependencies]
mimalloc = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
