using Avalonia.Controls;

namespace AetherVk.Views;

public partial class SettingsTabView : UserControl
{
  public SettingsTabView()
  {
    InitializeComponent();
  }
}

// DesignSettingsTabViewModel is generated by LocalizedStringsGenerator into
// AetherVk.Logic.ViewModels (aethervk.ui-logic assembly, #if DEBUG only).
// Nothing to declare here.
