[workspace]
members = [
  "aethervk.core/cdylib",
  "aethervk.core/rlib",
  "aethervk.oshal/rlib",
]
resolver = "3"
exclude = [
  "external/anise",
  "external/gltf",
  "external/vk-mem",
  "external/spirv-reflect",
  # this depends implicitly on `once_cell` which is also a dependency on `aethervk-oshal-rlib`.
  # `cargo check --all-targets` tries to be smart and unify all dependencies(normal, dev, build), including used features
  # `once_cell` feature = "std" sneaks into the rlib build, breaking it. Therefore, tests are excluded from our workspace
  "test/simulation_test",
  "test/anise_test",
]

# settings to strip and optimize release
# in rlib we don't care of how panic is handled
[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.dev]
panic = "abort"

### # 2. Override for a specific workspace member
### # NOTE: Use the actual package name (from the member's [package] block), 
### # NOT the folder name!
### [profile.dev.package.aethervk-oshal-rlib]
### opt-level = 3
### debug = false
### 
### # 3. You can override another member too
### [profile.dev.package.aethervk-core-rlib]
### opt-level = 2

### uncomment if necessary
## # Force all external crates (like ash, gltf, etc.) to be highly optimized
## [profile.dev.package."*"]
## opt-level = 3
