[workspace]
members = [
    "aethervk.core/cdylib",
    "aethervk.core/rlib",
    "aethervk.oshal/rlib",
    # "test/anise_test", # TODO having this no_std makes it run in cargo nextest run (Hijacks harness entry point?)
    "test/bezier_test",
    "test/compute_shaders_test",
    # "test/ellipse_rendering", # TODO FIX
    "test/mesh_viewer_test",
    "test/particle_force_test",
    # "test/particle_test", # TODO FIX
    "test/particles_motion_test",
    "test/physics_playground",
    "test/simulation_test",
    "test/test_paint",
    "test/test_ui",
    "test/test_utils",
    "test/windowless_export", "test_slotmap",
]
default-members = [
    "aethervk.core/cdylib",
    "aethervk.core/rlib",
    "aethervk.oshal/rlib",
]
resolver = "3"
exclude = [
    "test/anise_test", # TODO having this no_std makes it run in cargo nextest run (Hijacks harness entry point?)
    "test/ellipse_rendering", # TODO FIX
    "test/particle_test", # TODO FIX
    "external/anise",
    "external/gltf",
    "external/vk-mem",
    "external/spirv-reflect",
]

# settings to strip and optimize release
# in rlib we don't care of how panic is handled
[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.dev]
panic = "abort"

### # 2. Override for a specific workspace member
### # NOTE: Use the actual package name (from the member's [package] block), 
### # NOT the folder name!
### [profile.dev.package.aethervk-oshal-rlib]
### opt-level = 3
### debug = false
### 
### # 3. You can override another member too
### [profile.dev.package.aethervk-core-rlib]
### opt-level = 2

### uncomment if necessary
## # Force all external crates (like ash, gltf, etc.) to be highly optimized
## [profile.dev.package."*"]
## opt-level = 3
