#if DEBUG
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.Input;

namespace AetherVk.Logic.ViewModels;

/// <summary>
/// Hand-written partial extension for the design-time stub generated by
/// <c>[GenerateLocalizedStrings]</c>. Provides sample data for the
/// Avalonia XAML previewer for the non-localized members added via
/// <see cref="IModelTabViewModel"/>.
/// </summary>
public partial class DesignModelTabViewModel
{
  private static JetViewModel MakeSampleJet(int index)
  {
    var j = new JetViewModel { DisplayIndex = index };
    
    // Override random values with fixed sensible defaults for the design previewer
    if (index == 1)
    {
        j.LatitudeDeg = 30f;
        j.LongitudeDeg = 45f;
    }
    else
    {
        j.LatitudeDeg = -15f;
        j.LongitudeDeg = 120f;
    }
    
    return j;
  }

  public ObservableCollection<JetViewModel>? Jets { get; } = new()
  {
    MakeSampleJet(1),
    MakeSampleJet(2),
  };

  private JetViewModel? _selectedJet;
  public JetViewModel? SelectedJet
  {
    // Pre-select the first jet so the detail panel is visible in the previewer
    get => _selectedJet ??= Jets?[0];
    set => _selectedJet = value;
  }

  public IRelayCommand AddJetCommand    => new RelayCommand(() => { });
  public IRelayCommand<JetViewModel?> RemoveJetCommand => new RelayCommand<JetViewModel?>(_ => { });
  public float ManualNucleusRadiusKm { get; set; } = 2.0f;
  public float? ManualNucleusRadiusKmNullable { get; set; } = 2.0f;
  public bool IsNucleusRadiusUnknown => ManualNucleusRadiusKm == 0f;
  public bool ShowReferencePositionError { get; set; }
  public double DustSoftening { get; set; } = AetherVk.Logic.Services.ModelTabDefaults.DustSoftening;
  public bool DustTracers { get; set; } = false;
  public bool DustFlow { get; set; } = false;
  public double DustFlowSpeed { get; set; } = 1.0;
  public bool IsCometCommitted { get; } = false;
  public bool EnableLegacyExpanders { get; set; } = false;
  public bool IsSimulationRunning { get; } = false;
  
  public int IsGizmoVisibleIndex { get; set; } = 0;
  public string? StrPM { get; set; } = null;
  
  public AetherVk.Logic.Services.ModelSession? CurrentSession { get; } = new AetherVk.Logic.Services.ModelSession();

  public void SetCursorPosition(int x, int y) { }
}
#endif
