#if DEBUG
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.Input;

namespace AetherVk.Logic.ViewModels;

/// <summary>
/// Hand-written partial extension for the design-time stub generated by
/// <c>[GenerateLocalizedStrings]</c>. Provides sample data for the
/// Avalonia XAML previewer for the non-localized members added via
/// <see cref="IModelTabViewModel"/>.
/// </summary>
public partial class DesignModelTabViewModel
{
  private static JetViewModel MakeSampleJet(int index)
  {
    var j = new JetViewModel { DisplayIndex = index };
    return j;
  }

  public ObservableCollection<JetViewModel>? Jets { get; } = new()
  {
    MakeSampleJet(1),
    MakeSampleJet(2),
  };

  private JetViewModel? _selectedJet;
  public JetViewModel? SelectedJet
  {
    // Pre-select the first jet so the detail panel is visible in the previewer
    get => _selectedJet ??= Jets?[0];
    set => _selectedJet = value;
  }

  public IRelayCommand AddJetCommand    => new RelayCommand(() => { });
  public IRelayCommand<JetViewModel?> RemoveJetCommand => new RelayCommand<JetViewModel?>(_ => { });
  public float ManualNucleusRadiusKm { get; set; } = 0f;
  public float? ManualNucleusRadiusKmNullable { get; set; } = null;
  public bool IsNucleusRadiusUnknown => ManualNucleusRadiusKm == 0f;
}
#endif
