#if DEBUG
using System.Collections.ObjectModel;
using AetherVk.Logic.Models;
using CommunityToolkit.Mvvm.Input;

namespace AetherVk.Logic.ViewModels;

/// <summary>
/// Hand-written partial extension for the design-time stub generated by
/// <c>[GenerateLocalizedStrings]</c>. Provides sample data for the
/// Avalonia XAML previewer for the non-localized members added via
/// <see cref="ICometTabViewModel"/>.
/// </summary>
public partial class DesignCometTabViewModel
{
  // ── Proposed timeline ─────────────────────────────────────────────────────
  public string ProposedStartEpoch { get; } = "2015-08-01 00:00";
  public string ProposedEndEpoch   { get; } = "2016-01-01 00:00";
  public bool   HasProposedTimeline { get; } = true;

  // ── Search ────────────────────────────────────────────────────────────────
  public string SearchQuery { get; set; } = "67P";
  public bool   IsSearching { get; } = false;

  public ObservableCollection<CometSearchResult> SearchResults { get; } = new()
  {
    new CometSearchResult { Name = "67P/Churyumov-Gerasimenko", PrimaryDesignation = "67P" },
    new CometSearchResult { Name = "1P/Halley",                 PrimaryDesignation = "1P"  },
  };

  // FilteredSearchResults mirrors SearchResults at design time (no live filtering needed)
  public ObservableCollection<CometSearchResult> FilteredSearchResults { get; } = new()
  {
    new CometSearchResult { Name = "67P/Churyumov-Gerasimenko", PrimaryDesignation = "67P" },
    new CometSearchResult { Name = "1P/Halley",                 PrimaryDesignation = "1P"  },
  };

  private CometSearchResult? _selectedComet;
  public CometSearchResult? SelectedComet
  {
    get => _selectedComet ??= SearchResults[0];
    set => _selectedComet = value;
  }

  // ── SPK records ───────────────────────────────────────────────────────────
  public bool IsLoadingSpkRecords { get; } = false;

  public ObservableCollection<SpkRecordItem> SpkRecords { get; } = new()
  {
    new SpkRecordItem { RecordId = "90000033", EpochYear = "2015", MatchDesig = "67P", PrimaryDesig = "67P", Name = "67P/Churyumov-Gerasimenko" },
    new SpkRecordItem { RecordId = "90000034", EpochYear = "2016", MatchDesig = "67P", PrimaryDesig = "67P", Name = "67P/Churyumov-Gerasimenko" },
  };

  private SpkRecordItem? _selectedSpkRecord;
  public SpkRecordItem? SelectedSpkRecord
  {
    get => _selectedSpkRecord ??= SpkRecords[0];
    set => _selectedSpkRecord = value;
  }

  // ── Commit state ──────────────────────────────────────────────────────────
  public bool   IsAlmanacCommitted           { get; } = false;
  public string CommittedCometName           { get; } = string.Empty;
  public string DownloadStatus               { get; } = string.Empty;
  public bool   IsDownloading                { get; } = false;
  public bool   HasTimelineChangedAfterCommit { get; } = false;

  // ── Rotational model ──────────────────────────────────────────────────────
  public double PoleRaDeg        { get; set; } = 69.54;
  public double PoleDecDeg       { get; set; } = 64.11;
  public double PrimeMeridianDeg { get; set; } = 50.7;
  public double PoleRaRateDegCen { get; set; } = 0.0;
  public double PoleDecRateDegCen { get; set; } = 0.0;
  public double RotRateDegDay    { get; set; } = 696.0;

  // ── Commands (no-ops for design time) ────────────────────────────────────
  public IAsyncRelayCommand SearchCometsCommand    => new AsyncRelayCommand(async () => { });
  public IAsyncRelayCommand LoadSpkRecordsCommand  => new AsyncRelayCommand(async () => { });
  public IAsyncRelayCommand DownloadAndCommitCommand => new AsyncRelayCommand(async () => { });
  public IRelayCommand      DecommitCometCommand   => new RelayCommand(() => { });
}
#endif
