#if DEBUG
using System.Collections.Immutable;
using AetherVk.Logic.Services;
using CommunityToolkit.Mvvm.Input;

namespace AetherVk.Logic.ViewModels;

/// <summary>
/// Design-time stub implementation of the projection members on
/// <see cref="ISettingsTabViewModel"/>. The main <c>DesignSettingsTabViewModel</c>
/// class is auto-generated by <c>LocalizedStringsGenerator</c> into a separate
/// <c>.g.cs</c> file; this partial extends it with the hand-written interface members
/// so the AXAML previewer resolves all compiled bindings without errors.
/// </summary>
public partial class DesignSettingsTabViewModel
{
  public string CameraModeName  { get; } = "Up Zenith";
  public bool HasActiveViewport { get; } = true;

  public System.Collections.ObjectModel.ObservableCollection<ViewportSettingsViewModel> ActiveViewports { get; } = new();
}
#endif
