[package]
name = "aethervk-core-rlib"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

[lib]
name = "aethervk_core_rlib"
crate-type = ["rlib"]

# thanks to required features, the command is:
# `cargo test --test testbed --features --testbed`
# `cargo test` will exclude this
[[test]]
name = "testbed"
path = "testbed/main.rs"
harness = false
required-features = ["testbed"]

[features]
# Avalonia is X11 backed with XLib. There is some work for Avalonia 12 to have wayland though.
default = ["linux_xlib"]
std = []
linux_xlib = []
linux_xcb = []
linux_wayland = []
testbed = []

[dev-dependencies]
aethervk-oshal-rlib = { path = "../../aethervk.oshal/rlib", features = ["std"] }

[dependencies]
aethervk-oshal-rlib = { path = "../../aethervk.oshal/rlib" }
spin = { version = "0.10", features = ["once", "rwlock", "mutex"] }
thiserror = { version = "2", default-features = false }
bitflags = { version = "2.11", default-features = false }
heapless = { version = "0.9" }
itertools = { version = "0.14", default-features = false }
ouroboros = { version = "0.18" }
slotmap = { version = "1.1.1", default-features = false }

[target.'cfg(all(not(target_arch = "wasm32"), any( target_os = "windows", target_os = "linux", target_os = "macos", target_os = "android", target_os = "ios")))'.dependencies]
ash = { version = "0.38", default-features = false, features = ["debug"] }
vk-mem = { version = "0.5", path = "../../external/vk-mem", default-features = false, features = [
    "force-loaded",
] }

[target.'cfg(windows)'.dependencies]
windows = { version = ">=0.59, <=0.62", default-features = false, features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
] }

[target.'cfg(target_family = "unix")'.dependencies]
libc = { version = "0.2", default-features = false, features = [
    "extra_traits",
] }

# settings to strip and optimize release
# in rlib we don't care of how panic is handled
[profile.release]
lto = true
codegen-units = 1
strip = true
