using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AetherVk.SourceGenerators;

/// <summary>
/// Reads <c>AppStrings.resx</c> at build time and generates, for every partial class
/// annotated with <c>[GenerateLocalizedStrings(prefix)]</c>:
/// <list type="bullet">
///   <item><c>[ObservableProperty]</c> backing fields</item>
///   <item>A <c>RefreshStrings()</c> body calling <c>ITranslationService.GetString()</c></item>
///   <item>Partial-void stubs for formatted keys (values containing <c>{…}</c>)</item>
///   <item>The companion <c>IXxxViewModel</c> interface (string properties only)</item>
///   <item>A <c>#if DEBUG</c> design-time stub class with English fallback values</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class LocalizedStringsGenerator : IIncrementalGenerator
{
  // ── Attribute FQN ─────────────────────────────────────────────────────────────
  private const string AttributeFqn =
    "AetherVk.Logic.Attributes.GenerateLocalizedStringsAttribute";

  // ── Attribute source emitted into the consumer at every build ─────────────────
  private const string AttributeSource =
    """
    // <auto-generated/>
    #nullable enable
    using System;

    namespace AetherVk.Logic.Attributes
    {
        /// <summary>
        /// Instructs <c>LocalizedStringsGenerator</c> to emit localized string properties
        /// for all AppStrings.resx keys that start with <paramref name="keyPrefix"/>.
        /// </summary>
        [AttributeUsage(AttributeTargets.Class)]
        public sealed class GenerateLocalizedStringsAttribute : Attribute
        {
            /// <summary>Resx key prefix used to filter relevant keys.</summary>
            public string KeyPrefix   { get; }
            /// <summary>Value of the <c>Title</c> property in the generated design stub.</summary>
            public string DesignTitle { get; }
            /// <summary>Value of the <c>Icon</c> property in the generated design stub.</summary>
            public string DesignIcon  { get; }

            public GenerateLocalizedStringsAttribute(
                string keyPrefix,
                string designTitle = "",
                string designIcon  = "")
            {
                KeyPrefix   = keyPrefix;
                DesignTitle = designTitle;
                DesignIcon  = designIcon;
            }
        }
    }
    """;

  // ── Internal models (equatable for Roslyn's incremental caching) ──────────────
  private sealed class ClassModel : IEquatable<ClassModel>
  {
    public ClassModel(
      string namespaceName, string className,
      string keyPrefix, string designTitle, string designIcon)
    {
      Namespace   = namespaceName;
      ClassName   = className;
      KeyPrefix   = keyPrefix;
      DesignTitle = designTitle;
      DesignIcon  = designIcon;
    }

    public string Namespace   { get; }
    public string ClassName   { get; }
    public string KeyPrefix   { get; }
    public string DesignTitle { get; }
    public string DesignIcon  { get; }

    public bool Equals(ClassModel? other) =>
      other is not null &&
      Namespace   == other.Namespace   &&
      ClassName   == other.ClassName   &&
      KeyPrefix   == other.KeyPrefix   &&
      DesignTitle == other.DesignTitle &&
      DesignIcon  == other.DesignIcon;

    public override bool Equals(object? obj) => Equals(obj as ClassModel);
    public override int  GetHashCode()
    {
      unchecked
      {
        int h = Namespace.GetHashCode();
        h = h * 397 ^ ClassName.GetHashCode();
        h = h * 397 ^ KeyPrefix.GetHashCode();
        h = h * 397 ^ DesignTitle.GetHashCode();
        h = h * 397 ^ DesignIcon.GetHashCode();
        return h;
      }
    }
  }

  private sealed class ResxEntry
  {
    public ResxEntry(
      string fullKey, string propertyName, string fieldName,
      string designValue, bool isFormatted)
    {
      FullKey      = fullKey;
      PropertyName = propertyName;
      FieldName    = fieldName;
      DesignValue  = designValue;
      IsFormatted  = isFormatted;
    }

    public string FullKey      { get; }
    public string PropertyName { get; }
    public string FieldName    { get; }
    public string DesignValue  { get; }
    public bool   IsFormatted  { get; }
  }

  // ── Initialize ────────────────────────────────────────────────────────────────
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Always inject the attribute class into the consumer.
    context.RegisterPostInitializationOutput(static ctx =>
      ctx.AddSource("GenerateLocalizedStringsAttribute.g.cs", AttributeSource));

    // Collect AppStrings.resx registered as AdditionalFile.
    var resxProvider = context.AdditionalTextsProvider
      .Where(static f => f.Path.EndsWith(
        "AppStrings.resx", StringComparison.OrdinalIgnoreCase));

    // Collect classes decorated with [GenerateLocalizedStrings].
    var classProvider = context.SyntaxProvider
      .ForAttributeWithMetadataName(
        AttributeFqn,
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, ct) => ExtractModel(ctx, ct));

    // Emit three source files per decorated class × resx.
    context.RegisterSourceOutput(
      classProvider.Combine(resxProvider.Collect()),
      static (spc, pair) => Generate(spc, pair.Left, pair.Right));
  }

  // ── Model extraction ──────────────────────────────────────────────────────────
  private static ClassModel ExtractModel(
    GeneratorAttributeSyntaxContext ctx,
    CancellationToken ct)
  {
    ct.ThrowIfCancellationRequested();
    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
    var args   = ctx.Attributes[0].ConstructorArguments;

    return new ClassModel(
      namespaceName: symbol.ContainingNamespace.IsGlobalNamespace
                       ? string.Empty
                       : symbol.ContainingNamespace.ToDisplayString(),
      className:     symbol.Name,
      keyPrefix:     args.Length > 0 ? args[0].Value as string ?? string.Empty : string.Empty,
      designTitle:   args.Length > 1 ? args[1].Value as string ?? string.Empty : string.Empty,
      designIcon:    args.Length > 2 ? args[2].Value as string ?? string.Empty : string.Empty);
  }

  // ── Main generation ───────────────────────────────────────────────────────────
  private static void Generate(
    SourceProductionContext spc,
    ClassModel model,
    ImmutableArray<AdditionalText> resxFiles)
  {
    if (resxFiles.IsDefaultOrEmpty) return;

    var resxText = resxFiles[0].GetText(spc.CancellationToken)?.ToString();
    if (string.IsNullOrWhiteSpace(resxText)) return;

    List<ResxEntry> entries;
    try
    {
      entries = ParseResx(resxText!, model.KeyPrefix);
    }
    catch (Exception ex)
    {
      spc.ReportDiagnostic(Diagnostic.Create(
        new DiagnosticDescriptor(
          "AVK001", "Resx parse failure",
          $"LocalizedStringsGenerator could not parse AppStrings.resx: {ex.Message}",
          "AetherVk.SourceGenerators", DiagnosticSeverity.Warning, true),
        Location.None));
      return;
    }

    if (entries.Count == 0) return;

    var ifaceName  = "I" + model.ClassName;
    var designName = "Design" + model.ClassName;

    spc.AddSource(
      $"{model.ClassName}.LocalizedStrings.g.cs",
      BuildViewModelSource(model, entries));

    spc.AddSource(
      $"{ifaceName}.LocalizedStrings.g.cs",
      BuildInterfaceSource(model, ifaceName, entries));

    spc.AddSource(
      $"{designName}.LocalizedStrings.g.cs",
      BuildDesignSource(model, ifaceName, designName, entries));
  }

  // ── Resx parsing ──────────────────────────────────────────────────────────────
  private static List<ResxEntry> ParseResx(string xml, string prefix)
  {
    var entries = new List<ResxEntry>();
    var root    = XDocument.Parse(xml).Root;
    if (root is null) return entries;

    foreach (var data in root.Elements("data"))
    {
      var name = (string?)data.Attribute("name") ?? string.Empty;
      if (string.IsNullOrEmpty(name) ||
          !name.StartsWith(prefix, StringComparison.Ordinal)) continue;

      var typeAttr  = (string?)data.Attribute("type") ?? string.Empty;
      var isFileRef = typeAttr.Contains("ResXFileRef");
      var rawValue  = data.Element("value")?.Value ?? string.Empty;

      // FileRef values contain a file path — not useful as a design string.
      var designValue = isFileRef ? "[...]" : rawValue;
      // Formatted keys have {Placeholder} tokens in their value.
      var isFormatted = !isFileRef
        && rawValue.IndexOf('{') >= 0
        && rawValue.IndexOf('}') >= 0;

      var shortKey  = name.Substring(prefix.Length);
      var propBody  = ToPascalCase(shortKey);                         // e.g. HelpHeaderEccentricity
      var propName  = "Str" + propBody;                               // e.g. StrHelpHeaderEccentricity
      // CommunityToolkit strips leading '_' and treats the rest as camelCase to derive the property.
      // Convention: _strGeneral → strips '_', treats 's' as camelCase start → StrGeneral.
      // So the field must be _str + propBody (propBody already PascalCase, 'str' prefix is camelCase).
      var fieldName = "_str" + propBody;                              // e.g. _strHelpHeaderEccentricity

      entries.Add(new ResxEntry(name, propName, fieldName, designValue, isFormatted));
    }

    return entries;
  }

  /// <summary>
  /// Splits <paramref name="input"/> by '_', PascalCases each segment, and joins.
  /// <c>"Help_Header_Eccentricity"</c> → <c>"HelpHeaderEccentricity"</c>.
  /// </summary>
  private static string ToPascalCase(string input)
  {
    var parts = input.Split('_');
    var sb    = new StringBuilder();
    foreach (var part in parts)
    {
      if (part.Length == 0) continue;
      sb.Append(char.ToUpperInvariant(part[0]));
      if (part.Length > 1) sb.Append(part.Substring(1));
    }
    return sb.ToString();
  }

  // ── Source builders ───────────────────────────────────────────────────────────

  private static string BuildViewModelSource(ClassModel model, List<ResxEntry> entries)
  {
    var plain = entries.Where(static e => !e.IsFormatted).ToList();
    var fmt   = entries.Where(static e =>  e.IsFormatted).ToList();

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    AppendNamespace(sb, model.Namespace);

    sb.AppendLine($"partial class {model.ClassName}");
    sb.AppendLine("{");

    if (plain.Count > 0)
    {
      sb.AppendLine(
        "    // ── plain localized strings ─────────────────────────────────────────────");
      foreach (var e in plain)
      {
        sb.AppendLine($"    private string {e.FieldName} = string.Empty;");
        sb.AppendLine($"    public string {e.PropertyName}");
        sb.AppendLine( "    {");
        sb.AppendLine($"        get => {e.FieldName};");
        sb.AppendLine( "        set");
        sb.AppendLine( "        {");
        sb.AppendLine($"            if ({e.FieldName} == value) return;");
        sb.AppendLine($"            {e.FieldName} = value;");
        sb.AppendLine($"            OnPropertyChanged(nameof({e.PropertyName}));");
        sb.AppendLine( "        }");
        sb.AppendLine( "    }");
        sb.AppendLine();
      }
    }

    if (fmt.Count > 0)
    {
      sb.AppendLine(
        "    // ── formatted strings (implement the partial methods below) ─────────────");
      foreach (var e in fmt)
      {
        sb.AppendLine($"    private string {e.FieldName} = string.Empty;");
        sb.AppendLine($"    public string {e.PropertyName}");
        sb.AppendLine( "    {");
        sb.AppendLine($"        get => {e.FieldName};");
        sb.AppendLine( "        set");
        sb.AppendLine( "        {");
        sb.AppendLine($"            if ({e.FieldName} == value) return;");
        sb.AppendLine($"            {e.FieldName} = value;");
        sb.AppendLine($"            OnPropertyChanged(nameof({e.PropertyName}));");
        sb.AppendLine( "        }");
        sb.AppendLine( "    }");
        sb.AppendLine();
      }
    }

    sb.AppendLine(
      "    /// <summary>Called once on construction and on every culture change.</summary>");
    sb.AppendLine("    private void RefreshStrings()");
    sb.AppendLine("    {");

    foreach (var e in plain)
      sb.AppendLine(
        $"        {e.PropertyName} = _translationService.GetString(\"{e.FullKey}\");");

    foreach (var e in fmt)
    {
      var stub = e.PropertyName.Substring(3); // strip leading "Str"
      sb.AppendLine(
        $"        {{ var r = string.Empty; FormatStr_{stub}(ref r); {e.PropertyName} = r; }}");
    }

    sb.AppendLine("    }");

    if (fmt.Count > 0)
    {
      sb.AppendLine();
      sb.AppendLine(
        "    // ── Implement these in your hand-written partial class ───────────────────");
      foreach (var e in fmt)
      {
        var stub = e.PropertyName.Substring(3);
        sb.AppendLine($"    partial void FormatStr_{stub}(ref string result);");
      }
    }

    sb.AppendLine("}");
    return sb.ToString();
  }

  private static string BuildInterfaceSource(
    ClassModel model, string ifaceName, List<ResxEntry> entries)
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    AppendNamespace(sb, model.Namespace);

    sb.AppendLine($"public interface {ifaceName}");
    sb.AppendLine("{");
    foreach (var e in entries)
      sb.AppendLine($"    string {e.PropertyName} {{ get; set; }}");
    sb.AppendLine("}");
    return sb.ToString();
  }

  private static string BuildDesignSource(
    ClassModel model, string ifaceName, string designName, List<ResxEntry> entries)
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("#if DEBUG");
    sb.AppendLine();
    AppendNamespace(sb, model.Namespace);

    sb.AppendLine($"public class {designName} : {ifaceName}");
    sb.AppendLine("{");
    sb.AppendLine($"    public string Title    {{ get; set; }} = {Quote(model.DesignTitle)};");
    sb.AppendLine($"    public string Icon     {{ get; set; }} = {Quote(model.DesignIcon)};");
    sb.AppendLine( "    public bool   CanClose { get; set; } = true;");
    sb.AppendLine();
    foreach (var e in entries)
      sb.AppendLine($"    public string {e.PropertyName} {{ get; set; }} = {Quote(e.DesignValue)};");
    sb.AppendLine("}");
    sb.AppendLine("#endif");
    return sb.ToString();
  }

  // ── Helpers ───────────────────────────────────────────────────────────────────

  private static void AppendNamespace(StringBuilder sb, string namespaceName)
  {
    if (!string.IsNullOrEmpty(namespaceName))
    {
      sb.AppendLine($"namespace {namespaceName};");
      sb.AppendLine();
    }
  }

  private static string Quote(string s) =>
    "\"" + s
      .Replace("\\", "\\\\")
      .Replace("\"", "\\\"")
      .Replace("\r", "\\r")
      .Replace("\n", "\\n")
    + "\"";
}
