// @assets/sim/bp_bounds_gen.comp
#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_GOOGLE_include_directive : require

#include "../debug_utils.glsl"
#include "../bvh_utils.glsl"
#include "imex_math.glsl"

layout(local_size_x = 256) in;

layout(push_constant, std430) uniform PushConstants {
    RigidBodyArray scene_entities;
    LeafBuffer tlas_leaves;
    uvec2    dt_us;
    uint     total_entities;
} pc;

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= pc.total_entities) return;

    vec3 center = pc.scene_entities.bodies[id].position_mass.xyz;
    vec3 extents = pc.scene_entities.bodies[id].shape_extents;
    vec3 static_min = center - extents;
    vec3 static_max = center + extents;

    // Swept Volume based on velocity
    float dt = dt_to_seconds(pc.dt_us);
    vec3 vel = pc.scene_entities.bodies[id].linear_vel_drag.xyz;
    vec3 sweep = vel * dt;

    pc.tlas_leaves.leaves[id].min_bound = min(static_min, static_min + sweep);
    pc.tlas_leaves.leaves[id].max_bound = max(static_max, static_max + sweep);
    pc.tlas_leaves.leaves[id].entity_idx = id;
    pc.tlas_leaves.leaves[id].metadata = bvh_pack_metadata(true, BVH_FRAME_MACRO, pc.scene_entities.bodies[id].shape_type, id);
}