#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require

#include "../debug_utils.glsl"
#include "../bvh_utils.glsl"

#ifndef LOCAL_SIZE_X
#define LOCAL_SIZE_X 128
#endif
layout(local_size_x = LOCAL_SIZE_X, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, std430) uniform PushConstants {
    ParticleData aosoa_particles;
    RenderParticleDataArray mega_particles;
    IndirectArray mega_indirect;
    AtomicCounters atomic_counters;
    uint mega_indirect_index;
    uint mega_particle_offset;
} pc;


const uint PARTICLE_FIELDS = 11u;

void main() {
    uint total_particles = pc.atomic_counters.counts[0];

    // Only thread 0 writes the indirect command
    if (gl_GlobalInvocationID.x == 0) {
        pc.mega_indirect.commands[pc.mega_indirect_index].vertexCount = 4;
        pc.mega_indirect.commands[pc.mega_indirect_index].instanceCount = total_particles;
        pc.mega_indirect.commands[pc.mega_indirect_index].firstVertex = 0;
        pc.mega_indirect.commands[pc.mega_indirect_index].firstInstance = pc.mega_particle_offset;
    }

    uint idx = gl_GlobalInvocationID.x;
    if (idx >= total_particles) {
        return;
    }

    uint in_block = idx / SUBGROUP_SIZE;
    uint in_lane  = idx % SUBGROUP_SIZE;
    uint in_base  = in_block * PARTICLE_FIELDS * SUBGROUP_SIZE + in_lane;

    vec3 pos;
    pos.x = uintBitsToFloat(pc.aosoa_particles.data[in_base + 0 * SUBGROUP_SIZE]);
    pos.y = uintBitsToFloat(pc.aosoa_particles.data[in_base + 1 * SUBGROUP_SIZE]);
    pos.z = uintBitsToFloat(pc.aosoa_particles.data[in_base + 2 * SUBGROUP_SIZE]);

    vec3 vel;
    vel.x = uintBitsToFloat(pc.aosoa_particles.data[in_base + 3 * SUBGROUP_SIZE]);
    vel.y = uintBitsToFloat(pc.aosoa_particles.data[in_base + 4 * SUBGROUP_SIZE]);
    vel.z = uintBitsToFloat(pc.aosoa_particles.data[in_base + 5 * SUBGROUP_SIZE]);

    float mass = uintBitsToFloat(pc.aosoa_particles.data[in_base + 6 * SUBGROUP_SIZE]);

    uint out_idx = pc.mega_particle_offset + idx;

    // We do not have IDs or Age from the physics simulation right now.
    // They could be added in emit_particles.comp in the future.
    pc.mega_particles.data[out_idx].id_low = 0;
    pc.mega_particles.data[out_idx].id_high = 0;
    pc.mega_particles.data[out_idx].age_low = 0;
    pc.mega_particles.data[out_idx].age_high = 0;
    pc.mega_particles.data[out_idx].position = pos;
    pc.mega_particles.data[out_idx].mass = mass;
    pc.mega_particles.data[out_idx].velocity = vel;
    pc.mega_particles.data[out_idx].is_active = 1;
}