#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_GOOGLE_include_directive : require

#include "../bvh_utils.glsl"
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, std430) uniform PushConstants {
    MultiBvhBuffer bvh;
    AtomicCounters counters;
    uint num_internal_nodes;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x; if (idx >= pc.num_internal_nodes) return;
    pc.counters.counts[idx] = 0;
    if (idx == 0) pc.bvh.nodes[0].parent_idx = 0xFFFFFFFFu;
}
