#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_GOOGLE_include_directive : require

#include "../bvh_utils.glsl"
#include "imex_math.glsl"
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
layout(constant_id = 1) const uint PRIMITIVE_TYPE = 0;

layout(push_constant, std430) uniform PushConstants {
    MultiBvhBuffer bvh;
    ParticleData primitive_data;
    uint num_primitives;
    float dt;
    float particle_radius;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x; if (idx >= pc.num_primitives) return;

    if (PRIMITIVE_TYPE == 0) {
        uint base = P_BASE(idx);
        vec3 pos = vec3(pc.primitive_data.data[base+0], pc.primitive_data.data[base+1*SUBGROUP_SIZE], pc.primitive_data.data[base+2*SUBGROUP_SIZE]);
        vec3 vel = vec3(pc.primitive_data.data[base+3*SUBGROUP_SIZE], pc.primitive_data.data[base+4*SUBGROUP_SIZE], pc.primitive_data.data[base+5*SUBGROUP_SIZE]);

        vec3 p1 = pos + vel * pc.dt;
        vec3 min_p = min(pos, p1) - vec3(pc.particle_radius), max_p = max(pos, p1) + vec3(pc.particle_radius);

        uint leaf_idx = (pc.num_primitives - 1) + idx;
        uint parent = pc.bvh.nodes[leaf_idx].parent_idx;
        uint is_right = (pc.bvh.nodes[parent].child_indices[1] == leaf_idx) ? 1 : 0;

        pc.bvh.nodes[parent].min_x[is_right] = min_p.x; pc.bvh.nodes[parent].max_x[is_right] = max_p.x;
        pc.bvh.nodes[parent].min_y[is_right] = min_p.y; pc.bvh.nodes[parent].max_y[is_right] = max_p.y;
        pc.bvh.nodes[parent].min_z[is_right] = min_p.z; pc.bvh.nodes[parent].max_z[is_right] = max_p.z;
    }
}
