#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_GOOGLE_include_directive : require

#include "../bvh_utils.glsl"
#ifndef LOCAL_SIZE_X
#define LOCAL_SIZE_X 128
#endif
layout(local_size_x = LOCAL_SIZE_X, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, std430) uniform PushConstants {
    MultiBvhBuffer bvh;
    DepthIndices depth_indices;
    uint total_nodes_at_depth;
} pc;

void main() {
    uint global_id = gl_GlobalInvocationID.x; if (global_id >= pc.total_nodes_at_depth) return;

    uint node_idx = pc.depth_indices.indices[global_id + 4];
    for (uint i = 0; i < 2u; ++i) {
        uint child = tlas_child(pc.bvh, node_idx, i);
        if (bvh_is_leaf(tlas_metadata(pc.bvh, node_idx, i))) {
            tlas_write_min_x(pc.bvh, node_idx, i, tlas_min_x(pc.bvh, child, 0u)); tlas_write_max_x(pc.bvh, node_idx, i, tlas_max_x(pc.bvh, child, 0u));
            tlas_write_min_y(pc.bvh, node_idx, i, tlas_min_y(pc.bvh, child, 0u)); tlas_write_max_y(pc.bvh, node_idx, i, tlas_max_y(pc.bvh, child, 0u));
            tlas_write_min_z(pc.bvh, node_idx, i, tlas_min_z(pc.bvh, child, 0u)); tlas_write_max_z(pc.bvh, node_idx, i, tlas_max_z(pc.bvh, child, 0u));
        } else {
            tlas_write_min_x(pc.bvh, node_idx, i, min(tlas_min_x(pc.bvh, child, 0u), tlas_min_x(pc.bvh, child, 1u)));
            tlas_write_max_x(pc.bvh, node_idx, i, max(tlas_max_x(pc.bvh, child, 0u), tlas_max_x(pc.bvh, child, 1u)));
            tlas_write_min_y(pc.bvh, node_idx, i, min(tlas_min_y(pc.bvh, child, 0u), tlas_min_y(pc.bvh, child, 1u)));
            tlas_write_max_y(pc.bvh, node_idx, i, max(tlas_max_y(pc.bvh, child, 0u), tlas_max_y(pc.bvh, child, 1u)));
            tlas_write_min_z(pc.bvh, node_idx, i, min(tlas_min_z(pc.bvh, child, 0u), tlas_min_z(pc.bvh, child, 1u)));
            tlas_write_max_z(pc.bvh, node_idx, i, max(tlas_max_z(pc.bvh, child, 0u), tlas_max_z(pc.bvh, child, 1u)));
        }
    }
}
