#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_GOOGLE_include_directive : require

#include "../bvh_utils.glsl"
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, std430) uniform PushConstants {
    MultiBvhBuffer bvh;
    DepthIndices depth_indices;
    uint total_nodes_at_depth;
} pc;

void main() {
    uint global_id = gl_GlobalInvocationID.x; if (global_id >= pc.total_nodes_at_depth) return;

    uint node_idx = pc.depth_indices.indices[global_id + 4];
    for (uint i = 0; i < 2; ++i) {
        uint child = pc.bvh.nodes[node_idx].child_indices[i];
        if (bvh_is_leaf(pc.bvh.nodes[node_idx].metadata[i])) {
            pc.bvh.nodes[node_idx].min_x[i] = pc.bvh.nodes[child].min_x[0]; pc.bvh.nodes[node_idx].max_x[i] = pc.bvh.nodes[child].max_x[0];
            pc.bvh.nodes[node_idx].min_y[i] = pc.bvh.nodes[child].min_y[0]; pc.bvh.nodes[node_idx].max_y[i] = pc.bvh.nodes[child].max_y[0];
            pc.bvh.nodes[node_idx].min_z[i] = pc.bvh.nodes[child].min_z[0]; pc.bvh.nodes[node_idx].max_z[i] = pc.bvh.nodes[child].max_z[0];
        } else {
            pc.bvh.nodes[node_idx].min_x[i] = min(pc.bvh.nodes[child].min_x[0], pc.bvh.nodes[child].min_x[1]);
            pc.bvh.nodes[node_idx].max_x[i] = max(pc.bvh.nodes[child].max_x[0], pc.bvh.nodes[child].max_x[1]);
            pc.bvh.nodes[node_idx].min_y[i] = min(pc.bvh.nodes[child].min_y[0], pc.bvh.nodes[child].min_y[1]);
            pc.bvh.nodes[node_idx].max_y[i] = max(pc.bvh.nodes[child].max_y[0], pc.bvh.nodes[child].max_y[1]);
            pc.bvh.nodes[node_idx].min_z[i] = min(pc.bvh.nodes[child].min_z[0], pc.bvh.nodes[child].min_z[1]);
            pc.bvh.nodes[node_idx].max_z[i] = max(pc.bvh.nodes[child].max_z[0], pc.bvh.nodes[child].max_z[1]);
        }
    }
}
