#version 450 core
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_GOOGLE_include_directive : require

#include "../debug_utils.glsl"
#include "../bvh_utils.glsl"

#ifndef LOCAL_SIZE_X
#define LOCAL_SIZE_X 128
#endif
layout(local_size_x = LOCAL_SIZE_X, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, std430) uniform PushConstants {
    ParticleData particles;
    PackedCollisions collisions;
    OutputTOI out_toi;
    float particle_radius;
    float dt;
} pc;

// Size the array to the maximum possible number of subgroups (if subgroup size is 1)
shared uint shared_min_toi[128];

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    uint local_id = gl_LocalInvocationID.x;
    uint subgroup_id = gl_SubgroupID;

    float tc = pc.dt; // Default to max time

    if (global_id < pc.collisions.count) {
        tc = pc.collisions.pairs[global_id].toi;
        if (isnan(tc)) {
            tc = pc.dt;
        }
    }

    // Subgroup reduction
    float subgroup_min_tc = subgroupMin(tc);

    if (gl_SubgroupInvocationID == 0) {
        shared_min_toi[subgroup_id] = floatBitsToUint(subgroup_min_tc);
    }

    barrier();

    // Workgroup reduction
    if (local_id == 0) {
        uint num_subgroups = gl_WorkGroupSize.x / gl_SubgroupSize;
        // In case gl_SubgroupSize doesn't divide gl_WorkGroupSize.x perfectly:
        if ((gl_WorkGroupSize.x % gl_SubgroupSize) != 0) {
            num_subgroups += 1;
        }
        
        uint wg_min_uint = shared_min_toi[0];
        for (uint i = 1; i < num_subgroups; i++) {
            wg_min_uint = min(wg_min_uint, shared_min_toi[i]);
        }

        // Global reduction
        atomicMin(pc.out_toi.min_tc_uint, wg_min_uint);
    }
}
