[package]
name = "mesh_viewer_test"
version = "0.1.0"
edition = "2024"

[dependencies]
test_utils = { path = "../test_utils" }
aethervk-core-rlib = { path = "../../aethervk.core/rlib", default-features = false, features = ["std"] }
aethervk-oshal-rlib = { path = "../../aethervk.oshal/rlib", default-features = false, features = ["console_log"] }
anise = { version = "0.9.6", path = "../../external/anise/anise", default-features = false }
bytes = "1.11.1"
heapless = { version = "0.9" }
image = "0.25.10"
raw-window-handle = "0.6"
winit = { version = "0.29.15", features = ["rwh_06"] }
rfd = "0.14"

[target.'cfg(windows)'.dependencies]
windows = { version = ">=0.59, <= 0.62", default-features = false, features = [
  "Win32_Foundation",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }
windows-strings = { version = "0.5", default-features = false }
wchar = "0.11"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6.4", default-features = false }
objc2-core-foundation = { version = "0.3.2", default-features = false, features = [] }
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
  "NSResponder",
  "NSView",
  "objc2-quartz-core", 
  "NSWindow",          
] }
objc2-quartz-core = { version = "0.3.2", default-features = false, features = [
  "CALayer",
  "CAMetalLayer",
  "objc2-metal",
  "objc2-core-foundation", 
] }
objc2-foundation = { version = "0.3.2", default-features = false, features = [
  "NSNotification", 
  "NSString",       
] }
objc2-metal = { version = "0.3.2", default-features = false, features = [
  "MTLDevice",
] }

[features]
linux_wayland = ["aethervk-core-rlib/linux_wayland"]
linux_xlib = ["aethervk-core-rlib/linux_xlib"]
linux_xcb = ["aethervk-core-rlib/linux_xcb"]
physical_mesh_debug_normals = ["aethervk-core-rlib/physical_mesh_debug_normals"]
cursor_debug = ["aethervk-core-rlib/cursor_debug"]
spotless_rendering = []

