[package]
name = "particle_force_test"
version = "0.1.0"
edition = "2021"

[features]
use_vulkan_physics = []

[dependencies]
aethervk-core-rlib = { path = "../../aethervk.core/rlib" }
aethervk-oshal-rlib = { path = "../../aethervk.oshal/rlib" }
test_utils = { path = "../test_utils" }
winit = { version = "0.29.10" }
rayon = "1.10.0"
rand = "0.8.5"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6.4", default-features = false }
objc2-core-foundation = { version = "0.3.2", default-features = false, features = [] }
