use crate::math::collision::bounds::AABB;
use crate::math::collision::linear_bvh::{LinearBVH, LinearBVHHeader, LinearBVHNode, LinearBound};
use crate::math::physics::Particle;
use aethervk_oshal_rlib::math::vector::Vector3;
use aethervk_oshal_rlib::math::vector::{Vector, vec3::Vec3f32};
use alloc::vec::Vec;

// ============================================================================
// 1. Texture-Based Emission (Bilinear Sampling)
// ============================================================================

/// Represents a basic RGBA texture stored in host/device memory.
pub struct TextureRGBA {
  pub width: usize,
  pub height: usize,
  pub data: Vec<[f32; 4]>,
}

impl TextureRGBA {
  /// Bilinear interpolation to sample a color exactly at the UV coordinates
  /// generated by the `Distribution2D` (which is based on the Alpha channel).
  pub fn sample_bilinear(&self, u: f32, v: f32) -> [f32; 4] {
    let u = u.clamp(0.0, 1.0) * (self.width as f32 - 1.0);
    let v = v.clamp(0.0, 1.0) * (self.height as f32 - 1.0);

    let x0 = (u.floor() as usize).min(self.width - 1);
    let y0 = (v.floor() as usize).min(self.height - 1);
    let x1 = (x0 + 1).min(self.width - 1);
    let y1 = (y0 + 1).min(self.height - 1);

    let tx = u - x0 as f32;
    let ty = v - y0 as f32;

    let c00 = self.data[y0 * self.width + x0];
    let c10 = self.data[y0 * self.width + x1];
    let c01 = self.data[y1 * self.width + x0];
    let c11 = self.data[y1 * self.width + x1];

    let mut result = [0.0; 4];
    for i in 0..4 {
      let top = c00[i] * (1.0 - tx) + c10[i] * tx;
      let bottom = c01[i] * (1.0 - tx) + c11[i] * tx;
      result[i] = top * (1.0 - ty) + bottom * ty;
    }
    result
  }
}

// ============================================================================
// 2. Linear BVH Construction (Morton Codes)
// ============================================================================

/// Expands a 10-bit integer into 30 bits by inserting 2 zeros after each bit.
/// Essential for interleaving X, Y, Z bits to create the Z-Order curve.
#[inline(always)]
fn expand_bits(mut v: u32) -> u32 {
  v = (v * 0x00010001) & 0xFF0000FF;
  v = (v * 0x00000101) & 0x0F00F00F;
  v = (v * 0x00000011) & 0xC30C30C3;
  v = (v * 0x00000005) & 0x49249249;
  v
}

/// Calculates the 30-bit Morton Code (Z-Order) for a 3D point.
/// The point must be normalized into the [0.0, 1.0] range relative to the bounding box.
pub fn morton_3d(normalized_pos: Vec3f32) -> u32 {
  let x = (normalized_pos.x() * 1023.0).clamp(0.0, 1023.0) as u32;
  let y = (normalized_pos.y() * 1023.0).clamp(0.0, 1023.0) as u32;
  let z = (normalized_pos.z() * 1023.0).clamp(0.0, 1023.0) as u32;

  let xx = expand_bits(x);
  let yy = expand_bits(y);
  let zz = expand_bits(z);

  (xx << 2) | (yy << 1) | zz
}

// ============================================================================
// 2. Linear BVH Construction (Morton Codes & Radix Tree)
// ============================================================================

/// Helper: Count leading zeros of the XOR of two morton codes.
/// Used to find the length of the common prefix between two keys.
fn common_prefix(morton_codes: &[(u32, usize)], i: isize, j: isize) -> i32 {
  if j < 0 || j >= morton_codes.len() as isize {
    return -1;
  }
  let key1 = morton_codes[i as usize].0;
  let key2 = morton_codes[j as usize].0;

  if key1 == key2 {
    // If keys are identical, fallback to using their original array index to break ties
    let idx1 = morton_codes[i as usize].1 as u32;
    let idx2 = morton_codes[j as usize].1 as u32;
    return 32 + (idx1 ^ idx2).leading_zeros() as i32;
  }

  (key1 ^ key2).leading_zeros() as i32
}

/// Helper: Determines the range of nodes covered by an internal node `i`.
fn determine_range(morton_codes: &[(u32, usize)], i: usize) -> (usize, usize) {
  let i_isize = i as isize;
  let d = (common_prefix(morton_codes, i_isize, i_isize + 1)
    - common_prefix(morton_codes, i_isize, i_isize - 1))
  .signum() as isize;
  let min_prefix = common_prefix(morton_codes, i_isize, i_isize - d);

  let mut l_max = 2;
  while common_prefix(morton_codes, i_isize, i_isize + l_max * d) > min_prefix {
    l_max *= 2;
  }

  let mut l = 0;
  let mut t = l_max / 2;
  while t >= 1 {
    if common_prefix(morton_codes, i_isize, i_isize + (l + t) * d) > min_prefix {
      l += t;
    }
    t /= 2;
  }

  let j = i_isize + l * d;
  let min_idx = i_isize.min(j) as usize;
  let max_idx = i_isize.max(j) as usize;

  (min_idx, max_idx)
}

/// Helper: Finds the split position within the range `[first, last]`
fn find_split(morton_codes: &[(u32, usize)], first: usize, last: usize) -> usize {
  let first_isize = first as isize;
  let last_isize = last as isize;
  let common_prefix_node = common_prefix(morton_codes, first_isize, last_isize);

  let mut split = first_isize;
  let mut step = last_isize - first_isize;

  loop {
    step = (step + 1) >> 1; // ceil(step / 2)
    let new_split = split + step;

    if new_split < last_isize {
      let split_prefix = common_prefix(morton_codes, first_isize, new_split);
      if split_prefix > common_prefix_node {
        split = new_split;
      }
    }
    if step <= 1 {
      break;
    }
  }
  split as usize
}

/// Educational: Complete Radix-Tree based Linear BVH Construction.
/// This method is highly parallelizable and perfect for GPU implementation.
pub fn build_particle_lbvh(particles: &[Particle], particle_radius: f32) -> Option<LinearBVH<f32>> {
  if particles.is_empty() {
    return None;
  }

  let n = particles.len();

  // 1. Find global bounding box
  let mut min_b = particles[0].position;
  let mut max_b = particles[0].position;
  for p in particles {
    min_b = min_b.min(p.position);
    max_b = max_b.max(p.position);
  }
  let extent = max_b - min_b;

  // 2. Compute Morton code for each particle
  let mut morton_entries = Vec::with_capacity(n);
  for (i, p) in particles.iter().enumerate() {
    let normalized = if extent.length_squared() > 1e-8 {
      Vec3f32::from_components(
        (p.position.x() - min_b.x()) / extent.x(),
        (p.position.y() - min_b.y()) / extent.y(),
        (p.position.z() - min_b.z()) / extent.z(),
      )
    } else {
      Vec3f32::zero()
    };

    let code = morton_3d(normalized);
    morton_entries.push((code, i));
  }

  // 3. Sort by Morton Code
  morton_entries.sort_unstable_by_key(|&(code, _)| code);

  // 4. Allocate BVH Nodes.
  // A tree with N leaves has exactly N-1 internal nodes. Total = 2N - 1
  // We map internal nodes to indices 0..N-1, and leaf nodes to N..2N-2.
  let num_internal_nodes = n - 1;
  let num_total_nodes = 2 * n - 1;

  // Create a dummy node to initialize the array
  let dummy_node = LinearBVHNode {
    bound: LinearBound::AABB(AABB::new(Vec3f32::zero(), Vec3f32::zero())),
    left_child_or_primitive_offset: u32::MAX,
    right_child_offset: u32::MAX,
    primitive_count: 0,
  };

  let mut nodes = alloc::vec![dummy_node; num_total_nodes];
  let mut parent_pointers = alloc::vec![u32::MAX; num_total_nodes];

  // 5. Construct Hierarchy (Topology only)
  for i in 0..num_internal_nodes {
    let (first, last) = determine_range(&morton_entries, i);
    let split = find_split(&morton_entries, first, last);

    let left_child = if split == first {
      num_internal_nodes + split
    } else {
      split
    };

    let right_child = if split + 1 == last {
      num_internal_nodes + split + 1
    } else {
      split + 1
    };

    nodes[i].left_child_or_primitive_offset = left_child as u32;
    nodes[i].right_child_offset = right_child as u32;

    parent_pointers[left_child] = i as u32;
    parent_pointers[right_child] = i as u32;
  }

  // 6. Assign Leaf Nodes
  let mut primitives = Vec::with_capacity(n);
  for i in 0..n {
    let leaf_idx = num_internal_nodes + i;
    let original_particle_idx = morton_entries[i].1;
    let p = particles[original_particle_idx];

    // Leaf bounds encapsulate the particle radius
    let min_bound = p.position - Vec3f32::splat(particle_radius);
    let max_bound = p.position + Vec3f32::splat(particle_radius);

    nodes[leaf_idx].bound = LinearBound::AABB(AABB::new(min_bound, max_bound));
    nodes[leaf_idx].left_child_or_primitive_offset = i as u32; // Offset in primitives array
    nodes[leaf_idx].primitive_count = 1;

    primitives.push(original_particle_idx);
  }

  // 7. Calculate Bounding Boxes Bottom-Up
  // Since we're doing this on CPU sequentially, we can just process internal nodes backwards.
  // By processing from N-2 down to 0, we guarantee children are processed before parents.
  for i in (0..num_internal_nodes).rev() {
    let left_idx = nodes[i].left_child_or_primitive_offset as usize;
    let right_idx = nodes[i].right_child_offset as usize;

    let mut aabb = match &nodes[left_idx].bound {
      LinearBound::AABB(b) => b.clone(),
      _ => unreachable!(),
    };

    match &nodes[right_idx].bound {
      LinearBound::AABB(b) => aabb.encapsulate_aabb::<Vec3f32>(b),
      _ => unreachable!(),
    };

    nodes[i].bound = LinearBound::AABB(aabb);
  }

  Some(LinearBVH {
    header: LinearBVHHeader {
      preciseness: 0,
      node_count: num_total_nodes as u32,
      primitive_count: n as u32,
    },
    nodes,
    primitives,
  })
}

/// Educational: Fast BVH Refitting.
/// Updates the bounding boxes of an existing Linear BVH without changing its topology.
/// This is extremely fast, but the BVH quality will degrade over time as particles move chaotically.
pub fn update_particle_lbvh(
  bvh: &mut LinearBVH<f32>,
  particles: &[Particle],
  particle_radius: f32,
) {
  let n = bvh.primitives.len();
  if n <= 1 {
    if n == 1 {
      let original_idx = bvh.primitives[0];
      let p = &particles[original_idx];
      let min_bound = p.position - Vec3f32::splat(particle_radius);
      let max_bound = p.position + Vec3f32::splat(particle_radius);
      bvh.nodes[0].bound = LinearBound::AABB(AABB::new(min_bound, max_bound));
    }
    return;
  }

  let num_internal_nodes = n - 1;

  // 1. Update Leaf Nodes
  for i in 0..n {
    let leaf_idx = num_internal_nodes + i;
    let primitive_offset = bvh.nodes[leaf_idx].left_child_or_primitive_offset as usize;
    let original_particle_idx = bvh.primitives[primitive_offset];
    let p = &particles[original_particle_idx];

    let min_bound = p.position - Vec3f32::splat(particle_radius);
    let max_bound = p.position + Vec3f32::splat(particle_radius);

    bvh.nodes[leaf_idx].bound = LinearBound::AABB(AABB::new(min_bound, max_bound));
  }

  // 2. Recalculate Internal Nodes Bottom-Up
  // The topology guarantees that parent index < child indices (except for the leaves mapping).
  // Iterating backwards perfectly processes children before their parents.
  for i in (0..num_internal_nodes).rev() {
    let left_idx = bvh.nodes[i].left_child_or_primitive_offset as usize;
    let right_idx = bvh.nodes[i].right_child_offset as usize;

    let mut aabb = match &bvh.nodes[left_idx].bound {
      LinearBound::AABB(b) => b.clone(),
      _ => unreachable!(),
    };

    match &bvh.nodes[right_idx].bound {
      LinearBound::AABB(b) => aabb.encapsulate_aabb::<Vec3f32>(b),
      _ => unreachable!(),
    };

    bvh.nodes[i].bound = LinearBound::AABB(aabb);
  }
}

// ============================================================================
// 3. Temporal Clustering & Outlier Rejection
// ============================================================================

/// Represents a dust particle that has an age (in milliseconds)
#[derive(Debug, Clone, Copy)]
pub struct TemporalParticle {
  pub position: Vec3f32,
  pub age_ms: f32,
}

/// Clusters particles into age buckets and extracts a single, robust Center of Mass
/// for each bucket by rejecting statistical outliers (Z-Score filtering).
pub fn compute_robust_centroids(
  particles: &[TemporalParticle],
  bucket_size_ms: f32,
  z_score_threshold: f32,
) -> Vec<Vec3f32> {
  if particles.is_empty() {
    return Vec::new();
  }

  // Determine the max age to know how many buckets we need
  let max_age = particles.iter().fold(0.0f32, |acc, p| acc.max(p.age_ms));
  let num_buckets = (max_age / bucket_size_ms).ceil() as usize + 1;

  let mut buckets: Vec<Vec<Vec3f32>> = alloc::vec![Vec::new(); num_buckets];

  // 1. Group by age
  for p in particles {
    let bucket_idx = (p.age_ms / bucket_size_ms) as usize;
    buckets[bucket_idx].push(p.position);
  }

  let mut centroids = Vec::new();

  // 2. Process each bucket
  for bucket in buckets {
    if bucket.is_empty() {
      continue;
    }

    // Compute Mean (\mu)
    let mut mean = Vec3f32::zero();
    for &pos in &bucket {
      mean += pos;
    }
    mean /= bucket.len() as f32;

    // Compute Standard Deviation (\sigma)
    let mut variance = 0.0;
    for &pos in &bucket {
      variance += (pos - mean).length_squared();
    }
    let std_dev = (variance / bucket.len() as f32).sqrt();

    // 3. Outlier Rejection & Refined CoM
    let mut refined_mean = Vec3f32::zero();
    let mut inlier_count = 0;

    for &pos in &bucket {
      let dist = (pos - mean).length();

      // Z-Score = Distance / StdDev
      // If the particle is within `z_score_threshold` standard deviations, it's an inlier
      if std_dev < 1e-5 || (dist / std_dev) <= z_score_threshold {
        refined_mean += pos;
        inlier_count += 1;
      }
    }

    if inlier_count > 0 {
      refined_mean /= inlier_count as f32;
      centroids.push(refined_mean);
    }
  }

  centroids
}

// ============================================================================
// 4. Bezier Trajectory Generation
// ============================================================================

/// Represents a Rational Cubic Bezier Segment.
#[derive(Debug, Clone, Copy)]
pub struct CubicBezier {
  pub p0: Vec3f32,
  pub p1: Vec3f32,
  pub p2: Vec3f32,
  pub p3: Vec3f32,
}

impl CubicBezier {
  /// Evaluates the curve at parametric value t [0, 1]
  pub fn evaluate(&self, t: f32) -> Vec3f32 {
    let mt = 1.0 - t;
    let mt2 = mt * mt;
    let mt3 = mt2 * mt;
    let t2 = t * t;
    let t3 = t2 * t;

    self.p0 * mt3 + self.p1 * (3.0 * mt2 * t) + self.p2 * (3.0 * mt * t2) + self.p3 * t3
  }
}

/// Converts a sequence of robust centroids into a contiguous sequence of smooth Cubic Bezier curves
/// using the Centripetal Catmull-Rom spline formulation.
pub fn generate_bezier_trajectory(centroids: &[Vec3f32]) -> Vec<CubicBezier> {
  if centroids.len() < 2 {
    return Vec::new();
  }

  let mut beziers = Vec::with_capacity(centroids.len() - 1);

  for i in 0..(centroids.len() - 1) {
    // To build a Catmull-Rom segment between P_i and P_{i+1}, we need P_{i-1} and P_{i+2}.
    // We handle boundaries by duplicating endpoints (extrapolating velocity to zero).
    let p_prev = if i == 0 {
      centroids[0]
    } else {
      centroids[i - 1]
    };
    let p_curr = centroids[i];
    let p_next = centroids[i + 1];
    let p_next_next = if i + 2 >= centroids.len() {
      centroids[i + 1]
    } else {
      centroids[i + 2]
    };

    // Standard Catmull-Rom to Bezier matrix conversion:
    // B0 = P_i
    // B1 = P_i + (P_{i+1} - P_{i-1}) / 6
    // B2 = P_{i+1} - (P_{i+2} - P_i) / 6
    // B3 = P_{i+1}

    let b0 = p_curr;
    let b1 = p_curr + (p_next - p_prev) * (1.0 / 6.0);
    let b2 = p_next - (p_next_next - p_curr) * (1.0 / 6.0);
    let b3 = p_next;

    beziers.push(CubicBezier {
      p0: b0,
      p1: b1,
      p2: b2,
      p3: b3,
    });
  }

  beziers
}
