[env]
MACOSX_DEPLOYMENT_TARGET = "15.5"
RUST_TEST_THREADS = "1"
RUST_MIN_STACK = "8388608"

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-mmacosx-version-min=15.5"
]

[alias]
nt = "nextest run"

