//! time module.

#![allow(non_camel_case_types)]

use core::{
  cmp::min,
  sync::atomic::{AtomicI64, AtomicU32, Ordering},
};

#[cfg(windows)]
use windows::Win32::System::Performance::{QueryPerformanceCounter, QueryPerformanceFrequency};

#[cfg(any(target_os = "linux", target_os = "android"))]
use libc::{CLOCK_MONOTONIC, clock_gettime, timespec};

#[cfg(any(target_os = "macos", target_os = "ios"))]
use libc::{CLOCK_MONOTONIC_RAW, clock_gettime, timespec};

/// TODO: Document this item
pub type timeus_t = i64;

/// TODO: Document this item
pub const fn timeus_milliseconds(millis: u32) -> timeus_t {
  (millis as timeus_t) * 1_000
}

/// Converts microseconds (i64) to 1/300ths of a second (u32).
/// Rounds down (floor) to the nearest 1/300th.
pub fn us_to_300ths(time_us: i64) -> u32 {
  // 1. Handle negative values (clamp to 0)
  let time_us = if time_us > 0 { time_us } else { 0 };

  // 2. Perform the conversion: (time_us * 3) / 10,000
  let ticks = (time_us * 3) / 10_000;

  // 3. Convert down to u32, saturating at u32::MAX if it overflows
  // Note: unwrap_or(u32::MAX) acts as a saturating cast here if ticks > u32::MAX
  ticks.try_into().unwrap_or(u32::MAX)
}

/// Variant: Rounds to the *nearest* 1/300th instead of rounding down.
pub fn us_to_300ths_rounded(time_us: i64) -> u32 {
  let time_us = if time_us > 0 { time_us } else { 0 };

  // Add half the divisor (5,000) before dividing to round to nearest
  let ticks = (time_us * 3 + 5_000) / 10_000;

  ticks.try_into().unwrap_or(u32::MAX)
}

/// TODO: Document this item
pub fn get_monotonic_time() -> timeus_t {
  #[cfg(windows)]
  {
    static FREQUENCY: core::sync::atomic::AtomicI64 = core::sync::atomic::AtomicI64::new(0);

    let mut freq = FREQUENCY.load(core::sync::atomic::Ordering::Relaxed);
    if freq == 0 {
      unsafe { QueryPerformanceFrequency(&mut freq) };
      FREQUENCY.store(freq, core::sync::atomic::Ordering::Relaxed);
    }

    let mut counter = 0;
    unsafe { QueryPerformanceCounter(&mut counter) };

    // Convert directly to microseconds here!
    (counter * 1_000_000) / freq
  }
  #[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "macos",
    target_os = "ios"
  ))]
  {
    let mut tp: timespec = unsafe { core::mem::zeroed() };
    let clock_id: u32;
    #[cfg(any(target_os = "macos", target_os = "ios"))]
    {
      clock_id = CLOCK_MONOTONIC_RAW;
    }
    #[cfg(not(target_vendor = "apple"))]
    {
      clock_id = CLOCK_MONOTONIC as _;
    }
    unsafe { clock_gettime(clock_id as _, &mut tp) };
    (tp.tv_sec as timeus_t) * 1_000_000 + (tp.tv_nsec as timeus_t) / 1000
  }
}

pub mod v1 {
  use super::*;

  fn smooth(deltas: &[timeus_t; DELTAS_WINDOW_COUNT], start: usize) -> timeus_t {
    let mut index = start;
    let mut ema = deltas[index];
    for _ in 1..DELTAS_WINDOW_COUNT {
      index = (index + 1) % DELTAS_WINDOW_COUNT;
      ema = (ema + deltas[index]) / 2;
    }
    ema
  }

  /// Time information generated by the `TimeInfo` class
  #[derive(Debug, Default, Clone, Copy)]
  pub struct TimeReadings {
    pub time: timeus_t,
    pub fixed_time: timeus_t,
    pub delta_time: timeus_t,
    pub unscaled_time: timeus_t,
    pub unscaled_delta_time: timeus_t,
    pub smooth_delta_time: timeus_t,
  }

  const DELTAS_WINDOW_COUNT: usize = 4;
  const IDEAL_DELTA_TIME: timeus_t = 16_667; // 60 FPS

  // TODO remove completely
  /// Time information class inspired by the Unity Game Engine
  #[derive(Debug)]
  pub struct TimeInfo {
    pub fixed_delta_time: AtomicI64,
    pub maximum_delta_time: AtomicI64,
    time_scale: AtomicU32, // Stored as u32 bits of f32

    m_last_fixed_update: AtomicI64,
    m_last_real_update: AtomicI64,
    m_last_update: AtomicI64,

    m_start: timeus_t,

    m_deltas: [timeus_t; DELTAS_WINDOW_COUNT],
    m_last_raw_delta: AtomicI64,
    m_deltas_index: AtomicU32,
  }

  unsafe impl Sync for TimeInfo {}
  unsafe impl Send for TimeInfo {}

  impl TimeInfo {
    /// TODO: Document this item
    pub fn new(fixed_delta_time: timeus_t, maximum_delta_time: timeus_t, time_scale: f32) -> Self {
      assert!(fixed_delta_time <= maximum_delta_time);
      assert!(time_scale > 0.0);

      let start = get_monotonic_time();

      Self {
        fixed_delta_time: AtomicI64::new(fixed_delta_time),
        maximum_delta_time: AtomicI64::new(maximum_delta_time),
        time_scale: AtomicU32::new(time_scale.to_bits()),
        m_last_fixed_update: AtomicI64::new(start),
        m_last_real_update: AtomicI64::new(start),
        m_last_update: AtomicI64::new(start),
        m_start: start,
        m_deltas: [IDEAL_DELTA_TIME; DELTAS_WINDOW_COUNT],
        m_last_raw_delta: AtomicI64::new(0),
        m_deltas_index: AtomicU32::new(0),
      }
    }

    /// Discards the accumulated time debt to prevent a spiral of death.
    /// This aligns the fixed update tracker with the current simulated time.
    pub fn ut_discard_accumulator(&self) {
      let current_sim_time = self.m_last_update.load(Ordering::Relaxed);
      self.m_last_fixed_update.store(current_sim_time, Ordering::Relaxed);
    }

    /// TODO: Document this item
    pub fn set_time_scale(&mut self, time_scale: f32) {
      let time_scale = if time_scale > 0.0 { time_scale } else { 0.0 };
      self.time_scale.store(f32::to_bits(time_scale), Ordering::Relaxed);
    }

    /// TODO: Document this item
    pub fn get_time_scale(&mut self) -> f32 {
      f32::from_bits(self.time_scale.load(Ordering::Relaxed))
    }

    /// updates the real time and simulation time
    pub fn ut_update(&mut self) {
      let time_scale = f32::from_bits(self.time_scale.load(Ordering::Relaxed));
      assert!(time_scale > 0.0);

      let time_raw: i64 = get_monotonic_time();

      let delta_raw = time_raw - self.m_last_real_update.load(Ordering::Relaxed);
      let delta_scaled = (delta_raw as f32 * time_scale) as timeus_t;

      let delta = min(
        delta_scaled,
        self.maximum_delta_time.load(Ordering::Relaxed),
      );

      let idx = self.m_deltas_index.load(Ordering::Relaxed) as usize;
      // TODO array of refcells cause delta_index load protects this acces
      self.m_deltas[idx] = delta;
      self
        .m_deltas_index
        .store(((idx + 1) % DELTAS_WINDOW_COUNT) as u32, Ordering::Release);

      self.m_last_raw_delta.store(delta_raw, Ordering::Release);
      self.m_last_real_update.store(time_raw, Ordering::Release);
      self.m_last_update.fetch_add(delta, Ordering::Release);
    }

    /// update fixed time
    pub fn ut_fixed_update(&self) {
      let added = self.fixed_delta_time.load(Ordering::Relaxed);
      self.m_last_fixed_update.fetch_add(added, Ordering::Relaxed);
    }

    /// Returns the number of whole fixed-dt steps currently sitting in the
    /// accumulator (i.e. how many `ut_fixed_update` calls would be needed to
    /// drain it). Zero means the accumulator is not yet full.
    pub fn pending_fixed_steps(&self) -> u32 {
      let sim_time = self.m_last_update.load(Ordering::Relaxed);
      let fixed_time = self.m_last_fixed_update.load(Ordering::Relaxed);
      let lag = sim_time.saturating_sub(fixed_time).max(0);
      let fixed_dt = self.fixed_delta_time.load(Ordering::Relaxed).max(1);
      (lag / fixed_dt) as u32
    }

    /// TODO: Document this item
    pub fn needs_fixed_update(&self) -> bool {
      let fixed_delta = self.fixed_delta_time.load(Ordering::Relaxed);
      self.m_last_fixed_update.load(Ordering::Relaxed) + fixed_delta
        <= self.m_last_update.load(Ordering::Relaxed)
    }

    /// TODO: Document this item
    pub fn current(&self) -> TimeReadings {
      let idx = self.m_deltas_index.load(Ordering::Acquire) as usize;

      let mut deltas_copy = [0i64; DELTAS_WINDOW_COUNT];
      deltas_copy.copy_from_slice(&self.m_deltas);

      TimeReadings {
        time: self.m_last_update.load(Ordering::Acquire),
        fixed_time: self.m_last_fixed_update.load(Ordering::Acquire),
        delta_time: deltas_copy[idx],
        unscaled_time: self.m_last_real_update.load(Ordering::Acquire),
        unscaled_delta_time: self.m_last_raw_delta.load(Ordering::Acquire),
        smooth_delta_time: smooth(&deltas_copy, idx),
      }
    }
  }
}

pub mod v2 {
  use super::*;

  use core::cmp::min;

  // Using hifitime for no_std epoch tracking
  use hifitime::{Duration, Epoch};

  #[cfg(any(target_os = "linux", target_os = "android"))]
  use libc::CLOCK_MONOTONIC;
  #[cfg(any(target_os = "macos", target_os = "ios"))]
  use libc::CLOCK_MONOTONIC_RAW;
  #[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "macos",
    target_os = "ios"
  ))]
  use libc::{clock_gettime, timespec};
  #[cfg(windows)]
  use windows::Win32::System::Performance::{QueryPerformanceCounter, QueryPerformanceFrequency};

  // TODO move to core simulation layer
  // TODO FFI type in which positive integer maps to a state in order, while negative gets flipped
  // and mapped to custom
  /// Preset simulation speed
  #[derive(Debug, Clone, Copy, PartialEq)]
  pub enum SimSpeed {
    Paused,
    Realtime,
    OneHourPerSec,
    ThreeHoursPerSec,
    OneDayPerSec,
    Custom(f64),
  }

  impl SimSpeed {
    // TODO probably turn it into a integer
    /// returns the scale multiplier (eg 1 hour per second = 3600.0)
    pub fn scale_factor(&self) -> f64 {
      match self {
        SimSpeed::Paused => 0.0,
        SimSpeed::Realtime => 1.0,
        SimSpeed::OneHourPerSec => 3600.0,
        SimSpeed::ThreeHoursPerSec => 10800.0,
        SimSpeed::OneDayPerSec => 86400.0,
        SimSpeed::Custom(s) => *s,
      }
    }
  }

  /// Plain data struct holding the exact stat3e of time at a given frame.
  /// Wrapped in `Arc<RwLock<TimeState>>` for thread-safe, tear-free sharing
  #[derive(Debug, Clone, Copy)]
  pub struct TimeState {
    /// unscaled time (μs) for UI and rendering animations
    pub unscaled_time: timeus_t,
    /// unscaled time delta (μs) for UI and rendering animations
    pub unscaled_delta: timeus_t,

    /// scaled time (μs) for physics simulation
    pub scaled_time: timeus_t,
    /// scaled time delta (μs) for physics simulation
    pub scaled_delta: timeus_t,

    /// leftover scaled time tat hasn't been simulated yet
    pub scaled_accumulator: timeus_t,

    /// active speed preest
    pub speed: SimSpeed,
  }

  /// Main time controller, owned by logic thread
  pub struct TimeManager {
    /// The shared state accessible by rendering and UI threads
    pub state: alloc::sync::Arc<spin::RwLock<TimeState>>,

    /// the base epoch mapping `scaled_time = 0` to a real-world celestial date
    pub start_epoch: Epoch,

    /// Monotonic clock tracking
    start_monotonic: timeus_t,
    last_monotonic: timeus_t,

    /// configuration
    /// eg 100ms, to prevent spiral of death
    pub max_unscaled_delta: timeus_t,
  }

  impl TimeManager {
    pub fn new(start_epoch: Epoch, initial_speed: SimSpeed, max_unscaled_delta_ms: u32) -> Self {
      let now_us = get_monotonic_time();
      let state = TimeState {
        speed: initial_speed,
        unscaled_time: 0,
        unscaled_delta: 0,
        scaled_time: 0,
        scaled_delta: 0,
        scaled_accumulator: 0,
      };

      Self {
        state: alloc::sync::Arc::new(spin::RwLock::new(state)),
        start_epoch,
        start_monotonic: now_us,
        last_monotonic: now_us,
        max_unscaled_delta: (max_unscaled_delta_ms as timeus_t) * 1_000,
      }
    }

    /// Sets a new simulation speed
    pub fn set_speed(&mut self, speed: SimSpeed) {
      let mut state = self.state.write();
      state.speed = speed;
    }

    /// Called exactly once per main loop iteration
    pub fn tick(&mut self) {
      let now = get_monotonic_time();

      // calculate raw real-world time passed
      let mut unscaled_delta = now - self.last_monotonic;
      self.last_monotonic = now;

      // clamp to prevent the spiral of death if the thread slept too long or was suspended
      unscaled_delta = min(unscaled_delta, self.max_unscaled_delta);

      let mut state = self.state.write();
      let scale = state.speed.scale_factor();
      // f64 -> u64 for delta no problem
      let scaled_delta = (unscaled_delta as f64 * scale) as timeus_t;

      state.unscaled_delta = unscaled_delta;
      state.unscaled_time += unscaled_delta;

      state.scaled_delta = scaled_delta;
      state.scaled_time += scaled_delta;

      // accumulate physics time
      state.scaled_accumulator += scaled_delta;
    }

    /// consumes a fixed step from the accumulator. returns `true` if a step was consumed
    /// Used to drive velocity vertlet integration
    pub fn consume_fixed_step(&mut self, scaled_fixed_dt: timeus_t) -> bool {
      let mut state = self.state.write();
      if state.scaled_accumulator >= scaled_fixed_dt {
        state.scaled_accumulator -= scaled_fixed_dt;
        true
      } else {
        false
      }
    }

    /// Calculates the exact [`hifitime::Epoch`] for the current simulation frame.
    /// This combines the startnig epoch with the current scaled elapsed time
    pub fn current_epoch(&self) -> Epoch {
      let state = self.state.read();
      // convert microseconds to seconds for hifitime
      // f64 conv. works up to ~285.4 years -> 9,007,199,254,740,992 -> should be fine
      let duration = Duration::from_microseconds(state.scaled_time as _);
      self.start_epoch + duration
    }

    /// Yields/sleeps the caller thread if rendering/simulating too fast to enforce a max unscaled
    /// FPS
    pub fn govern_framerate(&self, target_fps: u32) {
      let target_frame_time = 1_000_000 / target_fps as timeus_t;
      let elapsed = get_monotonic_time() - self.last_monotonic;
      if elapsed < target_frame_time {
        let sleep_us = target_frame_time - elapsed;
        crate::os::native::this_thread::sleep_for(core::time::Duration::from_micros(sleep_us as _));
      }
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_time_info_initialization() {
    let fixed_dt = timeus_milliseconds(16);
    let max_dt = timeus_milliseconds(33);
    let time_info = TimeInfo::new(fixed_dt, max_dt, 1.0);

    let readings = time_info.current();
    assert_eq!(readings.delta_time, IDEAL_DELTA_TIME);
  }

  #[test]
  fn test_time_scale() {
    let fixed_dt = timeus_milliseconds(16);
    let max_dt = timeus_milliseconds(33);
    let mut time_info = TimeInfo::new(fixed_dt, max_dt, 1.0);

    time_info.set_time_scale(2.0);
    assert_eq!(time_info.get_time_scale(), 2.0);

    time_info.set_time_scale(-1.0); // should clamp to 0
    assert_eq!(time_info.get_time_scale(), 0.0);
  }
}
