#![allow(non_camel_case_types)]

use core::cmp::min;
use core::sync::atomic::{AtomicI64, AtomicU32, Ordering};

#[cfg(windows)]
use windows::Win32::System::Performance::{QueryPerformanceCounter, QueryPerformanceFrequency};

#[cfg(any(target_os = "linux", target_os = "android"))]
use libc::{CLOCK_MONOTONIC, clock_gettime, timespec};

#[cfg(any(target_os = "macos", target_os = "ios"))]
use libc::{CLOCK_MONOTONIC_RAW, clock_gettime, timespec};

pub type timeus_t = i64;

pub const fn timeus_milliseconds(millis: u32) -> timeus_t {
  (millis as timeus_t) * 1_000
}

/// Time information generated by the `TimeInfo` class
#[derive(Debug, Default, Clone, Copy)]
pub struct TimeReadings {
  pub time: timeus_t,
  pub fixed_time: timeus_t,
  pub delta_time: timeus_t,
  pub unscaled_time: timeus_t,
  pub unscaled_delta_time: timeus_t,
  pub smooth_delta_time: timeus_t,
}

const DELTAS_WINDOW_COUNT: usize = 4;
const IDEAL_DELTA_TIME: timeus_t = 16_667; // 60 FPS

/// Time information class inspired by the Unity Game Engine
#[derive(Debug)]
pub struct TimeInfo {
  pub fixed_delta_time: AtomicI64,
  pub maximum_delta_time: AtomicI64,
  time_scale: AtomicU32, // Stored as u32 bits of f32

  m_last_fixed_update: AtomicI64,
  m_last_real_update: AtomicI64,
  m_last_update: AtomicI64,

  #[cfg(windows)]
  m_frequency: i64,
  m_start: timeus_t,

  m_deltas: [timeus_t; DELTAS_WINDOW_COUNT],
  m_last_raw_delta: AtomicI64,
  m_deltas_index: AtomicU32,
}

unsafe impl Sync for TimeInfo {}
unsafe impl Send for TimeInfo {}

pub fn get_monotonic_time() -> timeus_t {
  #[cfg(windows)]
  {
    let mut counter = 0;
    unsafe { QueryPerformanceCounter(&mut counter) };
    counter as timeus_t
  }
  #[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "macos",
    target_os = "ios"
  ))]
  {
    let mut tp: timespec = unsafe { core::mem::zeroed() };
    let clock_id: u32;
    #[cfg(any(target_os = "macos", target_os = "ios"))]
    {
      clock_id = CLOCK_MONOTONIC_RAW;
    }
    #[cfg(not(target_vendor = "apple"))]
    {
      clock_id = CLOCK_MONOTONIC as _;
    }
    unsafe { clock_gettime(clock_id, &mut tp) };
    (tp.tv_sec as timeus_t) * 1_000_000 + (tp.tv_nsec as timeus_t) / 1000
  }
}

impl TimeInfo {
  pub fn new(fixed_delta_time: timeus_t, maximum_delta_time: timeus_t, time_scale: f32) -> Self {
    assert!(fixed_delta_time <= maximum_delta_time);
    assert!(time_scale > 0.0);

    #[cfg(windows)]
    let (frequency, start) = {
      let mut freq = 0;
      unsafe { QueryPerformanceFrequency(&mut freq) };
      let start_time = get_monotonic_time();
      (freq, (start_time * 1_000_000) / freq)
    };
    #[cfg(not(windows))]
    let start = get_monotonic_time();

    Self {
      fixed_delta_time: AtomicI64::new(fixed_delta_time),
      maximum_delta_time: AtomicI64::new(maximum_delta_time),
      time_scale: AtomicU32::new(time_scale.to_bits()),
      m_last_fixed_update: AtomicI64::new(start),
      m_last_real_update: AtomicI64::new(start),
      m_last_update: AtomicI64::new(start),
      #[cfg(windows)]
      m_frequency: frequency,
      m_start: start,
      m_deltas: [IDEAL_DELTA_TIME; DELTAS_WINDOW_COUNT],
      m_last_raw_delta: AtomicI64::new(0),
      m_deltas_index: AtomicU32::new(0),
    }
  }

  pub fn set_time_scale(&mut self, time_scale: f32) {
    let time_scale = if time_scale > 0.0 { time_scale } else { 0.0 };
    self.time_scale.store(f32::to_bits(time_scale), Ordering::Relaxed);
  }

  pub fn get_time_scale(&mut self) -> f32 {
    f32::from_bits(self.time_scale.load(Ordering::Relaxed))
  }

  /// updates the real time and simulation time
  pub fn ut_update(&mut self) {
    let time_scale = f32::from_bits(self.time_scale.load(Ordering::Relaxed));
    assert!(time_scale > 0.0);

    let time_raw: i64;
    #[cfg(windows)]
    {
      time_raw = (get_monotonic_time() * 1_000_000) / self.m_frequency;
    }
    #[cfg(not(windows))]
    {
      time_raw = get_monotonic_time();
    }

    let delta_raw = time_raw - self.m_last_real_update.load(Ordering::Relaxed);
    let delta_scaled = (delta_raw as f32 * time_scale) as timeus_t;

    let delta = min(
      delta_scaled,
      self.maximum_delta_time.load(Ordering::Relaxed),
    );

    let idx = self.m_deltas_index.load(Ordering::Relaxed) as usize;
    self.m_deltas[idx] = delta;
    self.m_deltas_index.store(((idx + 1) % DELTAS_WINDOW_COUNT) as u32, Ordering::Release);

    self.m_last_raw_delta.store(delta_raw, Ordering::Release);
    self.m_last_real_update.store(time_raw, Ordering::Release);
    self.m_last_update.fetch_add(delta, Ordering::Release);
  }

  /// update fixed time
  pub fn ut_fixed_update(&self) {
    let added = self.fixed_delta_time.load(Ordering::Relaxed);
    self.m_last_fixed_update.fetch_add(added, Ordering::Relaxed);
  }

  pub fn needs_fixed_update(&self) -> bool {
    let fixed_delta = self.fixed_delta_time.load(Ordering::Relaxed);
    self.m_last_fixed_update.load(Ordering::Relaxed) + fixed_delta
      <= self.m_last_update.load(Ordering::Relaxed)
  }

  pub fn current(&self) -> TimeReadings {
    let idx = self.m_deltas_index.load(Ordering::Acquire) as usize;

    let mut deltas_copy = [0i64; DELTAS_WINDOW_COUNT];
    deltas_copy.copy_from_slice(&self.m_deltas);

    TimeReadings {
      time: self.m_last_update.load(Ordering::Acquire),
      fixed_time: self.m_last_fixed_update.load(Ordering::Acquire),
      delta_time: deltas_copy[idx],
      unscaled_time: self.m_last_real_update.load(Ordering::Acquire),
      unscaled_delta_time: self.m_last_raw_delta.load(Ordering::Acquire),
      smooth_delta_time: smooth(&deltas_copy, idx),
    }
  }
}

fn smooth(deltas: &[timeus_t; DELTAS_WINDOW_COUNT], start: usize) -> timeus_t {
  let mut index = start;
  let mut ema = deltas[index];
  for _ in 1..DELTAS_WINDOW_COUNT {
    index = (index + 1) % DELTAS_WINDOW_COUNT;
    ema = (ema + deltas[index]) / 2;
  }
  ema
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_time_info_initialization() {
    let fixed_dt = timeus_milliseconds(16);
    let max_dt = timeus_milliseconds(33);
    let time_info = TimeInfo::new(fixed_dt, max_dt, 1.0);

    let readings = time_info.current();
    assert_eq!(readings.delta_time, IDEAL_DELTA_TIME);
  }

  #[test]
  fn test_time_scale() {
    let fixed_dt = timeus_milliseconds(16);
    let max_dt = timeus_milliseconds(33);
    let mut time_info = TimeInfo::new(fixed_dt, max_dt, 1.0);

    time_info.set_time_scale(2.0);
    assert_eq!(time_info.get_time_scale(), 2.0);

    time_info.set_time_scale(-1.0); // should clamp to 0
    assert_eq!(time_info.get_time_scale(), 0.0);
  }
}
