#version 450 core
#extension GL_GOOGLE_include_directive : require

#include "debug_utils.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "bvh_utils.glsl"

layout(push_constant) uniform Push {
    BVHArray bvh1;
    BVHArray bvh2;
    BVHBlockArray bvhBlock;
    CollisionPairList outList;
    uint bvhBlockIndex;
} push;

DECLARE_SHARED_BVH_CACHE(my_cache);

void main() {
    // Test compilation of AOSOA collaborative loading
    CACHE_BLOCK_COLLABORATIVE(push.bvhBlock, push.bvhBlockIndex, my_cache);
    
    // Barrier to sync shared memory
    barrier();
    
    BVHNodeAABB node;
    FETCH_NODE_FROM_CACHE(my_cache, 0, node);

    // Test functions
    if (gl_GlobalInvocationID.x == 0) {
        computeSelfIntersections(push.bvh1, 0, push.outList);
        intersectTwoHierarchies(push.bvh1, 0, push.bvh2, 0, push.outList);
    }
}
