#version 450 core
#extension GL_GOOGLE_include_directive : require

#include "debug_utils.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "bvh_utils.glsl"

layout(push_constant) uniform Push {
    BVHArray bvh1;
    BVHArray bvh2;
    MultiBvhBuffer bvhBlock;
    CollisionPairList outList;
    uint bvhBlockIndex;
} push;

DECLARE_SHARED_BVH_CACHE(my_cache);

void main() {}
