<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>

    <!-- TODO: Differentiate by runtime? -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="Serilog" Version="4.3.0" />

    <PackageReference Include="AetherVk.Runtime" Version="1.0.0" />

  </ItemGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\AetherVk.Runtime\nuget\$(Configuration)\AetherVk.Runtime.nuget\runtimes\win-x64\native\*.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(MSBuildThisFileDirectory)..\AetherVk.Runtime\nuget\$(Configuration)\AetherVk.Runtime.nuget\runtimes\win-x64\native\*.pdb" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Y:\Aether-Vk\src\launcher\windows\AetherVk\AetherVk.Core\..\AetherVk.Runtime\nuget\Debug\AetherVk.Runtime.nuget\runtimes\win-x64\native\AetherVk.Runtime.dll" />
    <None Remove="Y:\Aether-Vk\src\launcher\windows\AetherVk\AetherVk.Core\..\AetherVk.Runtime\nuget\Debug\AetherVk.Runtime.nuget\runtimes\win-x64\native\AetherVk.Runtime.pdb" />
  </ItemGroup>

</Project>
