#include "avk-android-dbg-utils.h"

// are they the same of game activity? Yes it should
#include <android/input.h>
#include <android/keycodes.h>

// TODO avoid in release builds

namespace avk::dbg {

char const* stringFromMotionEventAction(int actionMasked) {
  switch (actionMasked) {
    // when a touch event starts. Includes X,Y of touch
    case AMOTION_EVENT_ACTION_DOWN:
      return "AMOTION_EVENT_ACTION_DOWN";
      // Current Gesture has been aborted (programmatically?)
    case AMOTION_EVENT_ACTION_CANCEL:
      return "AMOTION_EVENT_ACTION_CANCEL";
      // change in coordinates between action down and cancel/up
    case AMOTION_EVENT_ACTION_MOVE:
      return "AMOTION_EVENT_ACTION_MOVE";
      // pressure gesture has successfully finished
    case AMOTION_EVENT_ACTION_UP:
      return "AMOTION_EVENT_ACTION_UP";
    default:
      return "<ignored>";
  }
}

char const* stringFromKeyCode(int keyCode) {
  switch (keyCode) {
    case AKEYCODE_SOFT_LEFT:
      return "AKEYCODE_SOFT_LEFT";
    case AKEYCODE_SOFT_RIGHT:
      return "AKEYCODE_SOFT_RIGHT";
    case AKEYCODE_HOME:
      return "AKEYCODE_HOME";
    case AKEYCODE_BACK:
      return "AKEYCODE_BACK";
    case AKEYCODE_CALL:
      return "AKEYCODE_CALL";
    case AKEYCODE_ENDCALL:
      return "AKEYCODE_ENDCALL";
    case AKEYCODE_0:
      return "AKEYCODE_0";
    case AKEYCODE_1:
      return "AKEYCODE_1";
    case AKEYCODE_2:
      return "AKEYCODE_2";
    case AKEYCODE_3:
      return "AKEYCODE_3";
    case AKEYCODE_4:
      return "AKEYCODE_4";
    case AKEYCODE_5:
      return "AKEYCODE_5";
    case AKEYCODE_6:
      return "AKEYCODE_6";
    case AKEYCODE_7:
      return "AKEYCODE_7";
    case AKEYCODE_8:
      return "AKEYCODE_8";
    case AKEYCODE_9:
      return "AKEYCODE_9";
    case AKEYCODE_STAR:
      return "AKEYCODE_STAR";
    case AKEYCODE_POUND:
      return "AKEYCODE_POUND";
    case AKEYCODE_DPAD_UP:
      return "AKEYCODE_DPAD_UP";
    case AKEYCODE_DPAD_DOWN:
      return "AKEYCODE_DPAD_DOWN";
    case AKEYCODE_DPAD_LEFT:
      return "AKEYCODE_DPAD_LEFT";
    case AKEYCODE_DPAD_RIGHT:
      return "AKEYCODE_DPAD_RIGHT";
    case AKEYCODE_DPAD_CENTER:
      return "AKEYCODE_DPAD_CENTER";
    case AKEYCODE_VOLUME_UP:
      return "AKEYCODE_VOLUME_UP";
    case AKEYCODE_VOLUME_DOWN:
      return "AKEYCODE_VOLUME_DOWN";
    case AKEYCODE_POWER:
      return "AKEYCODE_POWER";
    case AKEYCODE_CAMERA:
      return "AKEYCODE_CAMERA";
    case AKEYCODE_CLEAR:
      return "AKEYCODE_CLEAR";
    case AKEYCODE_A:
      return "AKEYCODE_A";
    case AKEYCODE_B:
      return "AKEYCODE_B";
    case AKEYCODE_C:
      return "AKEYCODE_C";
    case AKEYCODE_D:
      return "AKEYCODE_D";
    case AKEYCODE_E:
      return "AKEYCODE_E";
    case AKEYCODE_F:
      return "AKEYCODE_F";
    case AKEYCODE_G:
      return "AKEYCODE_G";
    case AKEYCODE_H:
      return "AKEYCODE_H";
    case AKEYCODE_I:
      return "AKEYCODE_I";
    case AKEYCODE_J:
      return "AKEYCODE_J";
    case AKEYCODE_K:
      return "AKEYCODE_K";
    case AKEYCODE_L:
      return "AKEYCODE_L";
    case AKEYCODE_M:
      return "AKEYCODE_M";
    case AKEYCODE_N:
      return "AKEYCODE_N";
    case AKEYCODE_O:
      return "AKEYCODE_O";
    case AKEYCODE_P:
      return "AKEYCODE_P";
    case AKEYCODE_Q:
      return "AKEYCODE_Q";
    case AKEYCODE_R:
      return "AKEYCODE_R";
    case AKEYCODE_S:
      return "AKEYCODE_S";
    case AKEYCODE_T:
      return "AKEYCODE_T";
    case AKEYCODE_U:
      return "AKEYCODE_U";
    case AKEYCODE_V:
      return "AKEYCODE_V";
    case AKEYCODE_W:
      return "AKEYCODE_W";
    case AKEYCODE_X:
      return "AKEYCODE_X";
    case AKEYCODE_Y:
      return "AKEYCODE_Y";
    case AKEYCODE_Z:
      return "AKEYCODE_Z";
    case AKEYCODE_COMMA:
      return "AKEYCODE_COMMA";
    case AKEYCODE_PERIOD:
      return "AKEYCODE_PERIOD";
    case AKEYCODE_ALT_LEFT:
      return "AKEYCODE_ALT_LEFT";
    case AKEYCODE_ALT_RIGHT:
      return "AKEYCODE_ALT_RIGHT";
    case AKEYCODE_SHIFT_LEFT:
      return "AKEYCODE_SHIFT_LEFT";
    case AKEYCODE_SHIFT_RIGHT:
      return "AKEYCODE_SHIFT_RIGHT";
    case AKEYCODE_TAB:
      return "AKEYCODE_TAB";
    case AKEYCODE_SPACE:
      return "AKEYCODE_SPACE";
    case AKEYCODE_SYM:
      return "AKEYCODE_SYM";
    case AKEYCODE_EXPLORER:
      return "AKEYCODE_EXPLORER";
    case AKEYCODE_ENVELOPE:
      return "AKEYCODE_ENVELOPE";
    case AKEYCODE_ENTER:
      return "AKEYCODE_ENTER";
    case AKEYCODE_DEL:
      return "AKEYCODE_DEL";
    case AKEYCODE_GRAVE:
      return "AKEYCODE_GRAVE";
    case AKEYCODE_MINUS:
      return "AKEYCODE_MINUS";
    case AKEYCODE_EQUALS:
      return "AKEYCODE_EQUALS";
    case AKEYCODE_LEFT_BRACKET:
      return "AKEYCODE_LEFT_BRACKET";
    case AKEYCODE_RIGHT_BRACKET:
      return "AKEYCODE_RIGHT_BRACKET";
    case AKEYCODE_BACKSLASH:
      return "AKEYCODE_BACKSLASH";
    case AKEYCODE_SEMICOLON:
      return "AKEYCODE_SEMICOLON";
    case AKEYCODE_APOSTROPHE:
      return "AKEYCODE_APOSTROPHE";
    case AKEYCODE_SLASH:
      return "AKEYCODE_SLASH";
    case AKEYCODE_AT:
      return "AKEYCODE_AT";
    case AKEYCODE_NUM:
      return "AKEYCODE_NUM";
    case AKEYCODE_HEADSETHOOK:
      return "AKEYCODE_HEADSETHOOK";
    case AKEYCODE_FOCUS:
      return "AKEYCODE_FOCUS";
    case AKEYCODE_PLUS:
      return "AKEYCODE_PLUS";
    case AKEYCODE_MENU:
      return "AKEYCODE_MENU";
    case AKEYCODE_NOTIFICATION:
      return "AKEYCODE_NOTIFICATION";
    case AKEYCODE_SEARCH:
      return "AKEYCODE_SEARCH";
    case AKEYCODE_MEDIA_PLAY_PAUSE:
      return "AKEYCODE_MEDIA_PLAY_PAUSE";
    case AKEYCODE_MEDIA_STOP:
      return "AKEYCODE_MEDIA_STOP";
    case AKEYCODE_MEDIA_NEXT:
      return "AKEYCODE_MEDIA_NEXT";
    case AKEYCODE_MEDIA_PREVIOUS:
      return "AKEYCODE_MEDIA_PREVIOUS";
    case AKEYCODE_MEDIA_REWIND:
      return "AKEYCODE_MEDIA_REWIND";
    case AKEYCODE_MEDIA_FAST_FORWARD:
      return "AKEYCODE_MEDIA_FAST_FORWARD";
    case AKEYCODE_MUTE:
      return "AKEYCODE_MUTE";
    case AKEYCODE_PAGE_UP:
      return "AKEYCODE_PAGE_UP";
    case AKEYCODE_PAGE_DOWN:
      return "AKEYCODE_PAGE_DOWN";
    case AKEYCODE_PICTSYMBOLS:
      return "AKEYCODE_PICTSYMBOLS";
    case AKEYCODE_SWITCH_CHARSET:
      return "AKEYCODE_SWITCH_CHARSET";
    case AKEYCODE_BUTTON_A:
      return "AKEYCODE_BUTTON_A";
    case AKEYCODE_BUTTON_B:
      return "AKEYCODE_BUTTON_B";
    case AKEYCODE_BUTTON_C:
      return "AKEYCODE_BUTTON_C";
    case AKEYCODE_BUTTON_X:
      return "AKEYCODE_BUTTON_X";
    case AKEYCODE_BUTTON_Y:
      return "AKEYCODE_BUTTON_Y";
    case AKEYCODE_BUTTON_Z:
      return "AKEYCODE_BUTTON_Z";
    case AKEYCODE_BUTTON_L1:
      return "AKEYCODE_BUTTON_L1";
    case AKEYCODE_BUTTON_R1:
      return "AKEYCODE_BUTTON_R1";
    case AKEYCODE_BUTTON_L2:
      return "AKEYCODE_BUTTON_L2";
    case AKEYCODE_BUTTON_R2:
      return "AKEYCODE_BUTTON_R2";
    case AKEYCODE_BUTTON_THUMBL:
      return "AKEYCODE_BUTTON_THUMBL";
    case AKEYCODE_BUTTON_THUMBR:
      return "AKEYCODE_BUTTON_THUMBR";
    case AKEYCODE_BUTTON_START:
      return "AKEYCODE_BUTTON_START";
    case AKEYCODE_BUTTON_SELECT:
      return "AKEYCODE_BUTTON_SELECT";
    case AKEYCODE_BUTTON_MODE:
      return "AKEYCODE_BUTTON_MODE";
    case AKEYCODE_ESCAPE:
      return "AKEYCODE_ESCAPE";
    case AKEYCODE_FORWARD_DEL:
      return "AKEYCODE_FORWARD_DEL";
    case AKEYCODE_CTRL_LEFT:
      return "AKEYCODE_CTRL_LEFT";
    case AKEYCODE_CTRL_RIGHT:
      return "AKEYCODE_CTRL_RIGHT";
    case AKEYCODE_CAPS_LOCK:
      return "AKEYCODE_CAPS_LOCK";
    case AKEYCODE_SCROLL_LOCK:
      return "AKEYCODE_SCROLL_LOCK";
    case AKEYCODE_META_LEFT:
      return "AKEYCODE_META_LEFT";
    case AKEYCODE_META_RIGHT:
      return "AKEYCODE_META_RIGHT";
    case AKEYCODE_FUNCTION:
      return "AKEYCODE_FUNCTION";
    case AKEYCODE_SYSRQ:
      return "AKEYCODE_SYSRQ";
    case AKEYCODE_BREAK:
      return "AKEYCODE_BREAK";
    case AKEYCODE_MOVE_HOME:
      return "AKEYCODE_MOVE_HOME";
    case AKEYCODE_MOVE_END:
      return "AKEYCODE_MOVE_END";
    case AKEYCODE_INSERT:
      return "AKEYCODE_INSERT";
    case AKEYCODE_FORWARD:
      return "AKEYCODE_FORWARD";
    case AKEYCODE_MEDIA_PLAY:
      return "AKEYCODE_MEDIA_PLAY";
    case AKEYCODE_MEDIA_PAUSE:
      return "AKEYCODE_MEDIA_PAUSE";
    case AKEYCODE_MEDIA_CLOSE:
      return "AKEYCODE_MEDIA_CLOSE";
    case AKEYCODE_MEDIA_EJECT:
      return "AKEYCODE_MEDIA_EJECT";
    case AKEYCODE_MEDIA_RECORD:
      return "AKEYCODE_MEDIA_RECORD";
    case AKEYCODE_F1:
      return "AKEYCODE_F1";
    case AKEYCODE_F2:
      return "AKEYCODE_F2";
    case AKEYCODE_F3:
      return "AKEYCODE_F3";
    case AKEYCODE_F4:
      return "AKEYCODE_F4";
    case AKEYCODE_F5:
      return "AKEYCODE_F5";
    case AKEYCODE_F6:
      return "AKEYCODE_F6";
    case AKEYCODE_F7:
      return "AKEYCODE_F7";
    case AKEYCODE_F8:
      return "AKEYCODE_F8";
    case AKEYCODE_F9:
      return "AKEYCODE_F9";
    case AKEYCODE_F10:
      return "AKEYCODE_F10";
    case AKEYCODE_F11:
      return "AKEYCODE_F11";
    case AKEYCODE_F12:
      return "AKEYCODE_F12";
    case AKEYCODE_NUM_LOCK:
      return "AKEYCODE_NUM_LOCK";
    case AKEYCODE_NUMPAD_0:
      return "AKEYCODE_NUMPAD_0";
    case AKEYCODE_NUMPAD_1:
      return "AKEYCODE_NUMPAD_1";
    case AKEYCODE_NUMPAD_2:
      return "AKEYCODE_NUMPAD_2";
    case AKEYCODE_NUMPAD_3:
      return "AKEYCODE_NUMPAD_3";
    case AKEYCODE_NUMPAD_4:
      return "AKEYCODE_NUMPAD_4";
    case AKEYCODE_NUMPAD_5:
      return "AKEYCODE_NUMPAD_5";
    case AKEYCODE_NUMPAD_6:
      return "AKEYCODE_NUMPAD_6";
    case AKEYCODE_NUMPAD_7:
      return "AKEYCODE_NUMPAD_7";
    case AKEYCODE_NUMPAD_8:
      return "AKEYCODE_NUMPAD_8";
    case AKEYCODE_NUMPAD_9:
      return "AKEYCODE_NUMPAD_9";
    case AKEYCODE_NUMPAD_DIVIDE:
      return "AKEYCODE_NUMPAD_DIVIDE";
    case AKEYCODE_NUMPAD_MULTIPLY:
      return "AKEYCODE_NUMPAD_MULTIPLY";
    case AKEYCODE_NUMPAD_SUBTRACT:
      return "AKEYCODE_NUMPAD_SUBTRACT";
    case AKEYCODE_NUMPAD_ADD:
      return "AKEYCODE_NUMPAD_ADD";
    case AKEYCODE_NUMPAD_DOT:
      return "AKEYCODE_NUMPAD_DOT";
    case AKEYCODE_NUMPAD_COMMA:
      return "AKEYCODE_NUMPAD_COMMA";
    case AKEYCODE_NUMPAD_ENTER:
      return "AKEYCODE_NUMPAD_ENTER";
    case AKEYCODE_NUMPAD_EQUALS:
      return "AKEYCODE_NUMPAD_EQUALS";
    case AKEYCODE_NUMPAD_LEFT_PAREN:
      return "AKEYCODE_NUMPAD_LEFT_PAREN";
    case AKEYCODE_NUMPAD_RIGHT_PAREN:
      return "AKEYCODE_NUMPAD_RIGHT_PAREN";
    case AKEYCODE_VOLUME_MUTE:
      return "AKEYCODE_VOLUME_MUTE";
    case AKEYCODE_APP_SWITCH:
      return "AKEYCODE_APP_SWITCH";
    case AKEYCODE_BRIGHTNESS_DOWN:
      return "AKEYCODE_BRIGHTNESS_DOWN";
    case AKEYCODE_BRIGHTNESS_UP:
      return "AKEYCODE_BRIGHTNESS_UP";
    case AKEYCODE_MEDIA_AUDIO_TRACK:
      return "AKEYCODE_MEDIA_AUDIO_TRACK";
    case AKEYCODE_SLEEP:
      return "AKEYCODE_SLEEP";
    case AKEYCODE_WAKEUP:
      return "AKEYCODE_WAKEUP";
    case AKEYCODE_PAIRING:
      return "AKEYCODE_PAIRING";
    case AKEYCODE_MEDIA_TOP_MENU:
      return "AKEYCODE_MEDIA_TOP_MENU";
    case AKEYCODE_11:
      return "AKEYCODE_11";
    case AKEYCODE_12:
      return "AKEYCODE_12";
    case AKEYCODE_HELP:
      return "AKEYCODE_HELP";
    case AKEYCODE_NAVIGATE_PREVIOUS:
      return "AKEYCODE_NAVIGATE_PREVIOUS";
    case AKEYCODE_NAVIGATE_NEXT:
      return "AKEYCODE_NAVIGATE_NEXT";
    case AKEYCODE_NAVIGATE_IN:
      return "AKEYCODE_NAVIGATE_IN";
    case AKEYCODE_NAVIGATE_OUT:
      return "AKEYCODE_NAVIGATE_OUT";
    case AKEYCODE_STEM_PRIMARY:
      return "AKEYCODE_STEM_PRIMARY";
    case AKEYCODE_STEM_1:
      return "AKEYCODE_STEM_1";
    case AKEYCODE_STEM_2:
      return "AKEYCODE_STEM_2";
    case AKEYCODE_STEM_3:
      return "AKEYCODE_STEM_3";
    case AKEYCODE_DPAD_UP_LEFT:
      return "AKEYCODE_DPAD_UP_LEFT";
    case AKEYCODE_DPAD_DOWN_LEFT:
      return "AKEYCODE_DPAD_DOWN_LEFT";
    case AKEYCODE_DPAD_UP_RIGHT:
      return "AKEYCODE_DPAD_UP_RIGHT";
    case AKEYCODE_DPAD_DOWN_RIGHT:
      return "AKEYCODE_DPAD_DOWN_RIGHT";
    case AKEYCODE_MEDIA_SKIP_FORWARD:
      return "AKEYCODE_MEDIA_SKIP_FORWARD";
    case AKEYCODE_MEDIA_SKIP_BACKWARD:
      return "AKEYCODE_MEDIA_SKIP_BACKWARD";
    case AKEYCODE_MEDIA_STEP_FORWARD:
      return "AKEYCODE_MEDIA_STEP_FORWARD";
    case AKEYCODE_MEDIA_STEP_BACKWARD:
      return "AKEYCODE_MEDIA_STEP_BACKWARD";
    case AKEYCODE_SOFT_SLEEP:
      return "AKEYCODE_SOFT_SLEEP";
    case AKEYCODE_CUT:
      return "AKEYCODE_CUT";
    case AKEYCODE_COPY:
      return "AKEYCODE_COPY";
    case AKEYCODE_PASTE:
      return "AKEYCODE_PASTE";
    case AKEYCODE_SYSTEM_NAVIGATION_UP:
      return "AKEYCODE_SYSTEM_NAVIGATION_UP";
    case AKEYCODE_SYSTEM_NAVIGATION_DOWN:
      return "AKEYCODE_SYSTEM_NAVIGATION_DOWN";
    case AKEYCODE_SYSTEM_NAVIGATION_LEFT:
      return "AKEYCODE_SYSTEM_NAVIGATION_LEFT";
    case AKEYCODE_SYSTEM_NAVIGATION_RIGHT:
      return "AKEYCODE_SYSTEM_NAVIGATION_RIGHT";
    case AKEYCODE_ALL_APPS:
      return "AKEYCODE_ALL_APPS";
    case AKEYCODE_REFRESH:
      return "AKEYCODE_REFRESH";
    case AKEYCODE_THUMBS_UP:
      return "AKEYCODE_THUMBS_UP";
    case AKEYCODE_THUMBS_DOWN:
      return "AKEYCODE_THUMBS_DOWN";
    case AKEYCODE_PROFILE_SWITCH:
      return "AKEYCODE_PROFILE_SWITCH";
    case AKEYCODE_VIDEO_APP_1:
      return "AKEYCODE_VIDEO_APP_1";
    case AKEYCODE_VIDEO_APP_2:
      return "AKEYCODE_VIDEO_APP_2";
    case AKEYCODE_VIDEO_APP_3:
      return "AKEYCODE_VIDEO_APP_3";
    case AKEYCODE_VIDEO_APP_4:
      return "AKEYCODE_VIDEO_APP_4";
    case AKEYCODE_VIDEO_APP_5:
      return "AKEYCODE_VIDEO_APP_5";
    case AKEYCODE_VIDEO_APP_6:
      return "AKEYCODE_VIDEO_APP_6";
    case AKEYCODE_VIDEO_APP_7:
      return "AKEYCODE_VIDEO_APP_7";
    case AKEYCODE_VIDEO_APP_8:
      return "AKEYCODE_VIDEO_APP_8";
    case AKEYCODE_FEATURED_APP_1:
      return "AKEYCODE_FEATURED_APP_1";
    case AKEYCODE_FEATURED_APP_2:
      return "AKEYCODE_FEATURED_APP_2";
    case AKEYCODE_FEATURED_APP_3:
      return "AKEYCODE_FEATURED_APP_3";
    case AKEYCODE_FEATURED_APP_4:
      return "AKEYCODE_FEATURED_APP_4";
    case AKEYCODE_DEMO_APP_1:
      return "AKEYCODE_DEMO_APP_1";
    case AKEYCODE_DEMO_APP_2:
      return "AKEYCODE_DEMO_APP_2";
    case AKEYCODE_DEMO_APP_3:
      return "AKEYCODE_DEMO_APP_3";
    case AKEYCODE_DEMO_APP_4:
      return "AKEYCODE_DEMO_APP_4";
    case AKEYCODE_KEYBOARD_BACKLIGHT_DOWN:
      return "AKEYCODE_KEYBOARD_BACKLIGHT_DOWN";
    case AKEYCODE_KEYBOARD_BACKLIGHT_UP:
      return "AKEYCODE_KEYBOARD_BACKLIGHT_UP";
    case AKEYCODE_KEYBOARD_BACKLIGHT_TOGGLE:
      return "AKEYCODE_KEYBOARD_BACKLIGHT_TOGGLE";
    case AKEYCODE_STYLUS_BUTTON_PRIMARY:
      return "AKEYCODE_STYLUS_BUTTON_PRIMARY";
    case AKEYCODE_STYLUS_BUTTON_SECONDARY:
      return "AKEYCODE_STYLUS_BUTTON_SECONDARY";
    case AKEYCODE_STYLUS_BUTTON_TERTIARY:
      return "AKEYCODE_STYLUS_BUTTON_TERTIARY";
    case AKEYCODE_STYLUS_BUTTON_TAIL:
      return "AKEYCODE_STYLUS_BUTTON_TAIL";
    case AKEYCODE_RECENT_APPS:
      return "AKEYCODE_RECENT_APPS";
    case AKEYCODE_MACRO_1:
      return "AKEYCODE_MACRO_1";
    case AKEYCODE_MACRO_2:
      return "AKEYCODE_MACRO_2";
    case AKEYCODE_MACRO_3:
      return "AKEYCODE_MACRO_3";
    case AKEYCODE_MACRO_4:
      return "AKEYCODE_MACRO_4";
    case AKEYCODE_EMOJI_PICKER:
      return "AKEYCODE_EMOJI_PICKER";
    case AKEYCODE_SCREENSHOT:
      return "AKEYCODE_SCREENSHOT";
    default:
      return "<unknown>";
  }
}

}  // namespace avk::dbg