[package]
name = "simulation_test"
version = "0.1.0"
edition = "2024"

[dependencies]
aethervk-core-rlib = { path = "../../aethervk.core/rlib", default-features = false }
aethervk-oshal-rlib = { path = "../../aethervk.oshal/rlib", default-features = false }
heapless = { version = "0.9" }
raw-window-handle = "0.6"
winit = { version = "0.29", features = ["rwh_06"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2.7", default-features = false }

[features]
linux_wayland = ["aethervk-core-rlib/linux_wayland"]
linux_xlib = ["aethervk-core-rlib/linux_xlib"]
linux_xcb = ["aethervk-core-rlib/linux_xcb"]

